package dev.vanillaplusplus.vppquests.quest;

import com.google.gson.JsonObject;
import net.minecraft.resources.ResourceLocation;

/**
 * The 5 task types this pack's existing quest system already implements
 * ({@code pack/kubejs/server_scripts/quests.js}, generated by
 * {@code scripts/gen_quests.py}) - carried over verbatim so a future
 * generator/migration can port the existing 62 quests without inventing a
 * new schema. See DESIGN.md's GitHub issue #109 design-proposal section,
 * "Data model" subsection, for the JSON shape each of these mirrors.
 *
 * <p>Kept as a small sealed hierarchy of plain data records (no Mojang
 * {@code Codec} dispatch) - {@link dev.vanillaplusplus.vppquests.quest.QuestReloadListener}
 * hand-parses the {@code "type"} discriminator field the same way
 * {@code quests.js}'s generator already emits it, which keeps Phase A's
 * parsing code simple and easy to extend per-type rather than fighting a
 * polymorphic codec for a 5-case enum.
 */
public sealed interface QuestTask {

    /** Human-readable type discriminator, matches the JSON {@code "type"} field. */
    String type();

    /** One-line progress description for the GUI detail panel, e.g. "3/5 zombies killed". */
    String describeProgress(int currentCount);

    /** How many progress "ticks" complete this task - 1 for boolean-style tasks. */
    int targetCount();

    record Item(ResourceLocation item, int count, boolean consume, boolean onlyFromCrafting) implements QuestTask {
        @Override
        public String type() {
            return "item";
        }

        @Override
        public String describeProgress(int currentCount) {
            return Math.min(currentCount, count) + "/" + count + " " + item;
        }

        @Override
        public int targetCount() {
            return count;
        }
    }

    record Kill(ResourceLocation entity, int count) implements QuestTask {
        @Override
        public String type() {
            return "kill";
        }

        @Override
        public String describeProgress(int currentCount) {
            return Math.min(currentCount, count) + "/" + count + " " + entity + " killed";
        }

        @Override
        public int targetCount() {
            return count;
        }
    }

    record Dimension(ResourceLocation dimension) implements QuestTask {
        @Override
        public String type() {
            return "dimension";
        }

        @Override
        public String describeProgress(int currentCount) {
            return currentCount > 0 ? "Visited " + dimension : "Not yet visited " + dimension;
        }

        @Override
        public int targetCount() {
            return 1;
        }
    }

    record Gamestage(String stage) implements QuestTask {
        @Override
        public String type() {
            return "gamestage";
        }

        @Override
        public String describeProgress(int currentCount) {
            return currentCount > 0 ? "Stage reached: " + stage : "Stage not yet reached: " + stage;
        }

        @Override
        public int targetCount() {
            return 1;
        }
    }

    record Checkmark() implements QuestTask {
        @Override
        public String type() {
            return "checkmark";
        }

        @Override
        public String describeProgress(int currentCount) {
            return currentCount > 0 ? "Acknowledged" : "Not yet acknowledged";
        }

        @Override
        public int targetCount() {
            return 1;
        }
    }

    /**
     * Parses one task JSON object using the same {@code "type"} discriminator
     * {@code scripts/gen_quests.py} already emits. Ground-truthed against
     * {@code quests.js}'s actual 5 task-type field shapes, not guessed.
     */
    static QuestTask fromJson(JsonObject json) {
        String type = json.get("type").getAsString();
        return switch (type) {
            case "item" -> new Item(
                    ResourceLocation.parse(json.get("item").getAsString()),
                    json.has("count") ? json.get("count").getAsInt() : 1,
                    !json.has("consume") || json.get("consume").getAsBoolean(),
                    json.has("onlyFromCrafting") && json.get("onlyFromCrafting").getAsBoolean());
            case "kill" -> new Kill(
                    ResourceLocation.parse(json.get("entity").getAsString()),
                    json.has("count") ? json.get("count").getAsInt() : 1);
            case "dimension" -> new Dimension(ResourceLocation.parse(json.get("dimension").getAsString()));
            case "gamestage" -> new Gamestage(json.get("stage").getAsString());
            case "checkmark" -> new Checkmark();
            default -> throw new IllegalArgumentException("Unknown quest task type: " + type);
        };
    }
}
