package dev.vanillaplusplus.vppquests.quest;

import com.google.gson.JsonObject;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.item.ItemStack;

/**
 * The 5 task types this pack's existing quest system already implements
 * ({@code pack/kubejs/server_scripts/quests.js}, generated by
 * {@code scripts/gen_quests.py}) - carried over verbatim so a future
 * generator/migration can port the existing 62 quests without inventing a
 * new schema. See DESIGN.md's GitHub issue #109 design-proposal section,
 * "Data model" subsection, for the JSON shape each of these mirrors.
 *
 * <p>Kept as a small sealed hierarchy of plain data records (no Mojang
 * {@code Codec} dispatch) - {@link dev.vanillaplusplus.vppquests.quest.QuestReloadListener}
 * hand-parses the {@code "type"} discriminator field the same way
 * {@code quests.js}'s generator already emits it, which keeps Phase A's
 * parsing code simple and easy to extend per-type rather than fighting a
 * polymorphic codec for a 5-case enum.
 */
public sealed interface QuestTask {

    /** Human-readable type discriminator, matches the JSON {@code "type"} field. */
    String type();

    /** One-line progress description for the GUI detail panel, e.g. "3/5 zombies killed". */
    String describeProgress(int currentCount);

    /**
     * Human-readable, registry-resolved progress line for the GUI (GitHub
     * #164 item&nbsp;4): renders item/entity <em>display names</em> - and, for
     * tag-based item tasks, an "Any &lt;tag&gt;" phrasing - instead of the raw
     * {@code namespace:path} ids {@link #describeProgress(int)} emits. The
     * default falls back to the raw string so the four boolean-style task
     * types (which have no id worth prettifying) need no override.
     */
    default Component describe(int currentCount) {
        return Component.literal(describeProgress(currentCount));
    }

    /** How many progress "ticks" complete this task - 1 for boolean-style tasks. */
    int targetCount();

    /**
     * Title-cases a resource-location path segment for display, e.g.
     * {@code "andesite_alloy"} -> {@code "Andesite Alloy"}. Used only as the
     * last-resort readable form for tag ids (which have no {@code ItemStack}
     * display name to borrow) and unresolved ids.
     */
    private static String prettifyPath(String path) {
        StringBuilder out = new StringBuilder(path.length());
        boolean capNext = true;
        for (char c : path.toCharArray()) {
            if (c == '_' || c == '/') {
                out.append(' ');
                capNext = true;
            } else if (capNext) {
                out.append(Character.toUpperCase(c));
                capNext = false;
            } else {
                out.append(c);
            }
        }
        return out.toString();
    }

    record Item(ResourceLocation item, int count, boolean consume, boolean onlyFromCrafting, boolean tag) implements QuestTask {
        @Override
        public String type() {
            return "item";
        }

        @Override
        public String describeProgress(int currentCount) {
            return Math.min(currentCount, count) + "/" + count + " " + (tag ? "#" : "") + item;
        }

        @Override
        public Component describe(int currentCount) {
            return Component.literal(Math.min(currentCount, count) + "/" + count + " ").append(displayName());
        }

        /**
         * The player-facing name of what this task wants: a tag renders as
         * "Any &lt;Tag Path&gt;", a concrete item as its {@code ItemStack}
         * hover name (falling back to a title-cased path if the id is not in
         * the registry, e.g. a mod that isn't installed).
         */
        public Component displayName() {
            if (tag) {
                return Component.literal("Any " + prettifyPath(item.getPath()));
            }
            return BuiltInRegistries.ITEM.getOptional(item)
                    .map(resolved -> (Component) new ItemStack(resolved).getHoverName())
                    .orElseGet(() -> Component.literal(prettifyPath(item.getPath())));
        }

        @Override
        public int targetCount() {
            return count;
        }
    }

    record Kill(ResourceLocation entity, int count) implements QuestTask {
        @Override
        public String type() {
            return "kill";
        }

        @Override
        public String describeProgress(int currentCount) {
            return Math.min(currentCount, count) + "/" + count + " " + entity + " killed";
        }

        @Override
        public Component describe(int currentCount) {
            Component name = BuiltInRegistries.ENTITY_TYPE.getOptional(entity)
                    .map(EntityType::getDescription)
                    .orElseGet(() -> Component.literal(prettifyPath(entity.getPath())));
            return Component.literal(Math.min(currentCount, count) + "/" + count + " ").append(name)
                    .append(Component.literal(" killed"));
        }

        @Override
        public int targetCount() {
            return count;
        }
    }

    record Dimension(ResourceLocation dimension) implements QuestTask {
        @Override
        public String type() {
            return "dimension";
        }

        @Override
        public String describeProgress(int currentCount) {
            return currentCount > 0 ? "Visited " + dimension : "Not yet visited " + dimension;
        }

        @Override
        public int targetCount() {
            return 1;
        }
    }

    record Gamestage(String stage) implements QuestTask {
        @Override
        public String type() {
            return "gamestage";
        }

        @Override
        public String describeProgress(int currentCount) {
            return currentCount > 0 ? "Stage reached: " + stage : "Stage not yet reached: " + stage;
        }

        @Override
        public int targetCount() {
            return 1;
        }
    }

    record Checkmark() implements QuestTask {
        @Override
        public String type() {
            return "checkmark";
        }

        @Override
        public String describeProgress(int currentCount) {
            return currentCount > 0 ? "Acknowledged" : "Not yet acknowledged";
        }

        @Override
        public int targetCount() {
            return 1;
        }
    }

    /**
     * Parses one task JSON object using the same {@code "type"} discriminator
     * {@code scripts/gen_quests.py} already emits. Ground-truthed against
     * {@code quests.js}'s actual 5 task-type field shapes, not guessed.
     */
    static QuestTask fromJson(JsonObject json) {
        String type = json.get("type").getAsString();
        return switch (type) {
            case "item" -> {
                String rawItem = json.get("item").getAsString();
                boolean isTag = rawItem.startsWith("#");
                yield new Item(
                        ResourceLocation.parse(isTag ? rawItem.substring(1) : rawItem),
                        json.has("count") ? json.get("count").getAsInt() : 1,
                        !json.has("consume") || json.get("consume").getAsBoolean(),
                        json.has("onlyFromCrafting") && json.get("onlyFromCrafting").getAsBoolean(),
                        isTag);
            }
            case "kill" -> new Kill(
                    ResourceLocation.parse(json.get("entity").getAsString()),
                    json.has("count") ? json.get("count").getAsInt() : 1);
            case "dimension" -> new Dimension(ResourceLocation.parse(json.get("dimension").getAsString()));
            case "gamestage" -> new Gamestage(json.get("stage").getAsString());
            case "checkmark" -> new Checkmark();
            default -> throw new IllegalArgumentException("Unknown quest task type: " + type);
        };
    }
}
