// GENERATED by scripts/gen_achievements.py - do not hand-edit, re-run the script instead.
// Per-player lifetime achievement chains, replacing FTB Quests' old Lifetime Achievements
// chapter (removed in Phase 6 - see gen_quests.py's note and DESIGN.md).
const ACHIEVEMENT_CHAINS = [
  { key: "mob_kills", getter: "getMobKills", label: "Monster Slayer", category: "swords", thresholds: [50, 200, 800, 3200] },
  { key: "play_time", getter: "getPlayTime", label: "Dedicated Settler", category: "mining", thresholds: [24000, 96000, 384000, 1536000] },
  { key: "animals_bred", getter: "getAnimalsBred", label: "Animal Husbandry", category: "building", thresholds: [20, 80, 320, 1280] },
  { key: "fish_caught", getter: "getFishCaught", label: "Angler", category: "swimming", thresholds: [15, 60, 240, 960] },
]

let achievementTickCounter = 0

ServerEvents.tick(event => {
    achievementTickCounter++
    if (achievementTickCounter % 100 !== 0) return

    for (const player of event.server.players) {
        const data = player.persistentData
        for (const chain of ACHIEVEMENT_CHAINS) {
            const progressKey = `achv_${chain.key}_tier`
            const currentTier = data.contains(progressKey) ? data.getInt(progressKey) : 0
            if (currentTier >= chain.thresholds.length) continue

            const statValue = player.stats[chain.getter]()
            const nextThreshold = chain.thresholds[currentTier]
            if (statValue < nextThreshold) continue

            const newTier = currentTier + 1
            const numeral = ["I", "II", "III", "IV"][currentTier]
            const xpAmount = 60 * Math.pow(4, currentTier)

            data.putInt(progressKey, newTier)
            player.server.runCommandSilent(`puffish_skills experience add ${player.username} ${chain.category} ${xpAmount}`)
            player.tell(`Achievement unlocked: ${chain.label} ${numeral} (+${xpAmount} ${chain.category} XP)`)
        }
    }
})
