// GENERATED by scripts/gen_dailies.py - do not hand-edit, re-run the script instead.
// Per-player daily bounties, replacing FTB Quests' old Daily Bounties chapter (Phase 6).
const DAY_MS = 86400000

const ITEM_BOUNTIES = [
  { key: "item_minecraft_cobblestone", itemId: "minecraft:cobblestone", count: 64, category: "mining", xp: 20, label: "Turn in 64x Cobblestone" },
  { key: "item_minecraft_oak_log", itemId: "minecraft:oak_log", count: 32, category: "building", xp: 20, label: "Turn in 32x Oak Log" },
  { key: "item_minecraft_coal", itemId: "minecraft:coal", count: 32, category: "mining", xp: 25, label: "Turn in 32x Coal" },
  { key: "item_minecraft_iron_ingot", itemId: "minecraft:iron_ingot", count: 16, category: "mining", xp: 30, label: "Turn in 16x Iron Ingot" },
  { key: "item_minecraft_wheat", itemId: "minecraft:wheat", count: 32, category: "building", xp: 20, label: "Turn in 32x Wheat" },
  { key: "item_create_andesite_alloy", itemId: "create:andesite_alloy", count: 16, category: "building", xp: 30, label: "Turn in 16x Andesite Alloy" },
  { key: "item_minecraft_copper_ingot", itemId: "minecraft:copper_ingot", count: 16, category: "mining", xp: 30, label: "Turn in 16x Copper Ingot" },
  { key: "item_minecraft_string", itemId: "minecraft:string", count: 24, category: "swords", xp: 20, label: "Turn in 24x String" },
  { key: "item_minecraft_leather", itemId: "minecraft:leather", count: 16, category: "swords", xp: 20, label: "Turn in 16x Leather" },
  { key: "item_minecraft_sand", itemId: "minecraft:sand", count: 64, category: "building", xp: 20, label: "Turn in 64x Sand" },
]

const KILL_BOUNTIES = [
  { key: "kill_minecraft_zombie", entityId: "minecraft:zombie", count: 15, category: "swords", xp: 30, label: "Slay 15x Zombie" },
  { key: "kill_minecraft_skeleton", entityId: "minecraft:skeleton", count: 15, category: "bows", xp: 30, label: "Slay 15x Skeleton" },
  { key: "kill_minecraft_spider", entityId: "minecraft:spider", count: 15, category: "swords", xp: 30, label: "Slay 15x Spider" },
  { key: "kill_minecraft_creeper", entityId: "minecraft:creeper", count: 8, category: "swords", xp: 35, label: "Slay 8x Creeper" },
  { key: "kill_minecraft_drowned", entityId: "minecraft:drowned", count: 10, category: "swimming", xp: 35, label: "Slay 10x Drowned" },
  { key: "kill_minecraft_cod", entityId: "minecraft:cod", count: 10, category: "swimming", xp: 25, label: "Slay 10x Cod" },
  { key: "kill_minecraft_rabbit", entityId: "minecraft:rabbit", count: 10, category: "running", xp: 25, label: "Slay 10x Rabbit" },
  { key: "kill_minecraft_enderman", entityId: "minecraft:enderman", count: 5, category: "swords", xp: 45, label: "Slay 5x Enderman" },
]

function getProgress(player, key) {
    const data = player.persistentData
    const progressKey = `daily_${key}_progress`
    const cooldownKey = `daily_${key}_cooldown_until`
    return {
        progress: data.contains(progressKey) ? data.getInt(progressKey) : 0,
        cooldownUntil: data.contains(cooldownKey) ? data.getLong(cooldownKey) : 0,
    }
}

function setProgress(player, key, progress) {
    player.persistentData.putInt(`daily_${key}_progress`, progress)
}

function completeBounty(player, bounty) {
    player.persistentData.putInt(`daily_${bounty.key}_progress`, 0)
    player.persistentData.putLong(`daily_${bounty.key}_cooldown_until`, Date.now() + DAY_MS)
    player.server.runCommandSilent(`puffish_skills experience add ${player.username} ${bounty.category} ${bounty.xp}`)
    player.tell(`Daily complete: ${bounty.label} (+${bounty.xp} ${bounty.category} XP)`)
}

function addBountyProgress(player, bounty, amount) {
    const { progress, cooldownUntil } = getProgress(player, bounty.key)
    if (Date.now() < cooldownUntil) return
    const newProgress = progress + amount
    if (newProgress >= bounty.count) {
        completeBounty(player, bounty)
    } else {
        setProgress(player, bounty.key, newProgress)
    }
}

EntityEvents.death(event => {
    const killer = event.source.entity
    if (!killer || killer.type !== "minecraft:player") return
    const victimType = event.entity.type
    for (const bounty of KILL_BOUNTIES) {
        if (bounty.entityId === victimType) {
            addBountyProgress(killer, bounty, 1)
        }
    }
})

ServerEvents.commandRegistry(event => {
    const { commands: Commands } = event

    event.register(
        Commands.literal("turnin")
            .executes(ctx => {
                const player = ctx.source.playerOrException
                const stack = player.getMainHandItem()
                if (!stack || stack.isEmpty()) {
                    player.tell("Hold a stack of a bounty item to turn it in.")
                    return 0
                }
                const itemId = stack.id
                const bounty = ITEM_BOUNTIES.find(b => b.itemId === itemId)
                if (!bounty) {
                    player.tell(`${itemId} isn't a daily bounty item.`)
                    return 0
                }
                const { progress, cooldownUntil } = getProgress(player, bounty.key)
                if (Date.now() < cooldownUntil) {
                    player.tell(`${bounty.label} is already complete for today.`)
                    return 0
                }
                const needed = bounty.count - progress
                const take = Math.min(needed, stack.getCount())
                stack.setCount(stack.getCount() - take)
                addBountyProgress(player, bounty, take)
                player.tell(`Turned in ${take}x ${itemId} (${Math.min(progress + take, bounty.count)}/${bounty.count})`)
                return take
            })
    )

    event.register(
        Commands.literal("dailies")
            .executes(ctx => {
                const player = ctx.source.playerOrException
                player.tell("--- Daily Bounties ---")
                for (const bounty of ITEM_BOUNTIES.concat(KILL_BOUNTIES)) {
                    const { progress, cooldownUntil } = getProgress(player, bounty.key)
                    if (Date.now() < cooldownUntil) {
                        const hoursLeft = Math.ceil((cooldownUntil - Date.now()) / 3600000)
                        player.tell(`${bounty.label}: done (resets in ~${hoursLeft}h)`)
                    } else {
                        player.tell(`${bounty.label}: ${progress}/${bounty.count}`)
                    }
                }
                return 1
            })
    )
})
