// GENERATED by scripts/gen_economy.py - do not hand-edit, re-run the script instead.
// Tier-based sell pricing (in Numismatics spurs) + the /sell command that pays it out.
const DEFAULT_PRICE = 1
const ITEM_PRICES = {
  "create:brass_block": 16,
  "create:brass_ingot": 16,
  "create:brass_nugget": 16,
  "create:brass_sheet": 16,
  "create:controller_rail": 16,
  "create:deployer": 16,
  "create:display_board": 16,
  "create:display_link": 16,
  "create:elevator_pulley": 16,
  "create:mechanical_arm": 16,
  "create:portable_fluid_interface": 16,
  "create:portable_storage_interface": 16,
  "create:redstone_link": 16,
  "create:refined_radiance": 64,
  "create:sequenced_gearshift": 16,
  "create:shadow_steel": 64,
  "create:sturdy_sheet": 64,
  "createaddition:capacitor": 16,
  "createaddition:copper_rod": 16,
  "createaddition:copper_spool": 16,
  "createaddition:copper_wire": 16,
  "createaddition:iron_rod": 16,
  "createaddition:iron_wire": 16,
  "createaddition:spool": 16,
  "minecraft:activator_rail": 4,
  "minecraft:ancient_debris": 64,
  "minecraft:bucket": 4,
  "minecraft:clock": 4,
  "minecraft:compass": 4,
  "minecraft:deepslate_diamond_ore": 16,
  "minecraft:deepslate_iron_ore": 4,
  "minecraft:detector_rail": 4,
  "minecraft:diamond": 16,
  "minecraft:diamond_axe": 16,
  "minecraft:diamond_block": 16,
  "minecraft:diamond_boots": 16,
  "minecraft:diamond_chestplate": 16,
  "minecraft:diamond_helmet": 16,
  "minecraft:diamond_hoe": 16,
  "minecraft:diamond_leggings": 16,
  "minecraft:diamond_ore": 16,
  "minecraft:diamond_pickaxe": 16,
  "minecraft:diamond_shovel": 16,
  "minecraft:diamond_sword": 16,
  "minecraft:elytra": 64,
  "minecraft:flint_and_steel": 4,
  "minecraft:iron_axe": 4,
  "minecraft:iron_block": 4,
  "minecraft:iron_boots": 4,
  "minecraft:iron_chestplate": 4,
  "minecraft:iron_helmet": 4,
  "minecraft:iron_hoe": 4,
  "minecraft:iron_ingot": 4,
  "minecraft:iron_leggings": 4,
  "minecraft:iron_ore": 4,
  "minecraft:iron_pickaxe": 4,
  "minecraft:iron_shovel": 4,
  "minecraft:iron_sword": 4,
  "minecraft:minecart": 4,
  "minecraft:netherite_axe": 64,
  "minecraft:netherite_block": 64,
  "minecraft:netherite_boots": 64,
  "minecraft:netherite_chestplate": 64,
  "minecraft:netherite_helmet": 64,
  "minecraft:netherite_hoe": 64,
  "minecraft:netherite_ingot": 64,
  "minecraft:netherite_leggings": 64,
  "minecraft:netherite_pickaxe": 64,
  "minecraft:netherite_scrap": 64,
  "minecraft:netherite_shovel": 64,
  "minecraft:netherite_sword": 64,
  "minecraft:powered_rail": 4,
  "minecraft:rail": 4,
  "minecraft:raw_iron": 4,
  "minecraft:raw_iron_block": 4,
  "minecraft:shears": 4,
  "minecraft:shield": 4,
  "minecraft:totem_of_undying": 64,
  "refinedstorage:1024b_fluid_storage_disk": 64,
  "refinedstorage:1024b_fluid_storage_part": 64,
  "refinedstorage:16k_storage_disk": 64,
  "refinedstorage:16k_storage_part": 64,
  "refinedstorage:1k_storage_disk": 16,
  "refinedstorage:1k_storage_part": 16,
  "refinedstorage:256b_fluid_storage_disk": 16,
  "refinedstorage:256b_fluid_storage_part": 16,
  "refinedstorage:4096b_fluid_storage_disk": 256,
  "refinedstorage:4096b_fluid_storage_part": 256,
  "refinedstorage:4k_storage_disk": 16,
  "refinedstorage:4k_storage_part": 16,
  "refinedstorage:64b_fluid_storage_disk": 16,
  "refinedstorage:64b_fluid_storage_part": 16,
  "refinedstorage:64k_storage_disk": 256,
  "refinedstorage:64k_storage_part": 256,
  "refinedstorage:advanced_processor": 256,
  "refinedstorage:autocrafting_upgrade": 256,
  "refinedstorage:basic_processor": 16,
  "refinedstorage:cable": 16,
  "refinedstorage:construction_core": 16,
  "refinedstorage:destruction_core": 16,
  "refinedstorage:fallback_security_card": 64,
  "refinedstorage:improved_processor": 16,
  "refinedstorage:machine_casing": 16,
  "refinedstorage:network_card": 64,
  "refinedstorage:pattern": 256,
  "refinedstorage:portable_grid": 64,
  "refinedstorage:processor_binding": 16,
  "refinedstorage:quartz_enriched_copper": 16,
  "refinedstorage:quartz_enriched_iron": 16,
  "refinedstorage:raw_advanced_processor": 256,
  "refinedstorage:raw_basic_processor": 16,
  "refinedstorage:raw_improved_processor": 16,
  "refinedstorage:security_card": 64,
  "refinedstorage:silicon": 16,
  "refinedstorage:storage_housing": 16,
  "refinedstorage:wireless_autocrafting_monitor": 256,
  "refinedstorage:wireless_grid": 64,
  "toms_storage:adv_wireless_terminal": 64,
  "toms_storage:inventory_configurator": 4,
  "toms_storage:item_filter": 4,
  "toms_storage:polymorphic_item_filter": 16,
  "toms_storage:tag_item_filter": 16,
  "toms_storage:wireless_terminal": 16,
}

function priceFor(itemId) {
    return ITEM_PRICES[itemId] !== undefined ? ITEM_PRICES[itemId] : DEFAULT_PRICE
}

// Coin denominations in spurs, largest first, matching Numismatics' own Coin
// enum (net.createmod...Coin / dev.ithundxr.createnumismatics...Coin):
// spur=1, bevel=8, sprocket=16, cog=64, crown=512, sun=4096.
const COINS = [
    ["numismatics:sun", 4096],
    ["numismatics:crown", 512],
    ["numismatics:cog", 64],
    ["numismatics:sprocket", 16],
    ["numismatics:bevel", 8],
    ["numismatics:spur", 1],
]

function payCoins(player, totalSpurs) {
    let remaining = totalSpurs
    for (const [itemId, value] of COINS) {
        const count = Math.floor(remaining / value)
        if (count > 0) {
            player.give(Item.of(itemId, count))
            remaining -= count * value
        }
    }
}

ServerEvents.commandRegistry(event => {
    const { commands: Commands, arguments: Arguments } = event

    event.register(
        Commands.literal("sell")
            .executes(ctx => {
                const player = ctx.source.playerOrException
                const stack = player.getMainHandItem()
                if (!stack || stack.isEmpty()) {
                    player.tell("Hold an item to sell it to the vendor.")
                    return 0
                }
                const itemId = stack.id
                const count = stack.getCount()
                const unitPrice = priceFor(itemId)
                const total = unitPrice * count
                stack.setCount(0)
                payCoins(player, total)
                player.tell(`Sold ${count}x ${itemId} for ${total} spurs.`)
                return total
            })
    )
})
