// GENERATED by scripts/gen_quests.py - do not hand-edit, re-run the script instead.
// Bespoke quest tracker replacing FTB Quests (GitHub #33) - see scripts/gen_quests.py's
// own module docstring for the full design rationale (team-shared progress / per-player
// rewards, the #32 party-id seam, the mod-removal evidence trail, and every disclosed
// content-fidelity simplification).
// 10 chapters, 62 quests, 87 dependency edges.
const QUEST_CHAPTERS = [
  {
    "id": "rootborn",
    "title": "Rootborn",
    "subtitle": [
      "The world is still just the world - for now."
    ],
    "icon": "minecraft:stone_pickaxe",
    "order": 0,
    "quests": [
      {
        "id": "rootborn__welcome",
        "title": "Welcome to Vanilla++",
        "desc": [
          "Punch some trees, then check this book after every tier-up - each chapter is a checklist for that tier's real progression."
        ],
        "icon": "minecraft:crafting_table",
        "dependencies": [],
        "tasks": [
          {
            "type": "checkmark"
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 10
          }
        ]
      },
      {
        "id": "rootborn__stone_age",
        "title": "Stone Age",
        "desc": [
          "Craft your first pickaxe through Silent Gear (any material) - the first real tool upgrade."
        ],
        "icon": "minecraft:stone_pickaxe",
        "dependencies": [
          "rootborn__welcome"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "silentgear:pickaxe",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 10
          }
        ]
      },
      {
        "id": "rootborn__first_hunt",
        "title": "First Blood",
        "desc": [
          "Kill a zombie. Combat matters from here on - Swords XP feeds directly into the RPG skill tree."
        ],
        "icon": "minecraft:iron_sword",
        "dependencies": [
          "rootborn__welcome"
        ],
        "tasks": [
          {
            "type": "kill",
            "entity": "minecraft:zombie",
            "count": 1
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 10
          }
        ]
      },
      {
        "id": "rootborn__gather_andesite",
        "title": "Into Create's Material Chain",
        "desc": [
          "Craft or pick up Andesite Alloy - Create's own entry material, and the trigger for Andesite Age."
        ],
        "icon": "create:andesite_alloy",
        "dependencies": [
          "rootborn__stone_age",
          "rootborn__first_hunt"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "create:andesite_alloy",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "item",
            "item": "numismatics:spur",
            "count": 2
          },
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 20
          }
        ]
      }
    ]
  },
  {
    "id": "andesite_age",
    "title": "Andesite Age",
    "subtitle": [
      "Iron enters the world. Create's own machinery begins."
    ],
    "icon": "create:andesite_alloy",
    "order": 1,
    "quests": [
      {
        "id": "andesite_age__enter",
        "title": "Enter the Andesite Age",
        "desc": [
          "Iron tools and Create's own machinery are open. This chapter is your Andesite Age checklist."
        ],
        "icon": "create:andesite_alloy",
        "dependencies": [
          "rootborn__gather_andesite"
        ],
        "tasks": [
          {
            "type": "gamestage",
            "stage": "andesite_age"
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 80
          },
          {
            "type": "item",
            "item": "create:andesite_alloy",
            "count": 1
          }
        ]
      },
      {
        "id": "andesite_age__iron_tools",
        "title": "Iron Tools",
        "desc": [
          "Craft another Silent Gear pickaxe with this tier's material - the real mining-speed upgrade this tier unlocks."
        ],
        "icon": "minecraft:iron_pickaxe",
        "dependencies": [
          "andesite_age__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "silentgear:pickaxe",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 30
          },
          {
            "type": "item",
            "item": "numismatics:spur",
            "count": 2
          }
        ]
      },
      {
        "id": "andesite_age__dumb_storage",
        "title": "Dumb Storage",
        "desc": [
          "Craft a Tom's Storage Inventory Connector - link your chests into one browsable network. No power, no autocrafting yet."
        ],
        "icon": "toms_storage:inventory_connector",
        "dependencies": [
          "andesite_age__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "toms_storage:inventory_connector",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 30
          },
          {
            "type": "item",
            "item": "numismatics:spur",
            "count": 2
          }
        ]
      },
      {
        "id": "andesite_age__jetpack_1",
        "title": "Copper Jetpack",
        "desc": [
          "Craft the Copper Jetpack - the first rung of the personal mobility ladder (Create Stuff & Additions)."
        ],
        "icon": "create_sa:copper_jetpack_chestplate",
        "dependencies": [
          "andesite_age__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "create_sa:copper_jetpack_chestplate",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 30
          },
          {
            "type": "item",
            "item": "numismatics:spur",
            "count": 2
          }
        ]
      },
      {
        "id": "andesite_age__chunk_loader_1",
        "title": "Andesite Chunk Loader",
        "desc": [
          "Craft the Andesite Chunk Loader (Create: Power Loader). It only force-loads chunks while spun under real kinetic power."
        ],
        "icon": "create_power_loader:andesite_chunk_loader",
        "dependencies": [
          "andesite_age__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "create_power_loader:andesite_chunk_loader",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 30
          },
          {
            "type": "item",
            "item": "numismatics:spur",
            "count": 2
          }
        ]
      },
      {
        "id": "andesite_age__vein_hunting",
        "title": "Vein Hunting",
        "desc": [
          "Craft a Vein Finder (Create Ore Excavation) - the entry-level scouting tool for this pack's ore-vein system."
        ],
        "icon": "createoreexcavation:vein_finder",
        "dependencies": [
          "andesite_age__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "createoreexcavation:vein_finder",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 30
          },
          {
            "type": "item",
            "item": "numismatics:spur",
            "count": 2
          }
        ]
      },
      {
        "id": "andesite_age__ars_wand",
        "title": "The Mage's Path",
        "desc": [
          "Craft an Ars Nouveau wand - the entry point into this pack's spell-crafting magic system."
        ],
        "icon": "ars_nouveau:wand",
        "dependencies": [
          "andesite_age__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "ars_nouveau:wand",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 30
          },
          {
            "type": "item",
            "item": "numismatics:spur",
            "count": 2
          }
        ]
      },
      {
        "id": "andesite_age__curious_find",
        "title": "A Curious Find (optional)",
        "desc": [
          "Find any Artifacts curio - they're pure exploration payoffs with no tier lock, hidden in structure loot at every rarity tier. This one just confirms you've found the umbrella."
        ],
        "icon": "artifacts:umbrella",
        "dependencies": [
          "andesite_age__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "artifacts:umbrella",
            "count": 1,
            "consume": false,
            "onlyFromCrafting": false
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 30
          }
        ]
      },
      {
        "id": "andesite_age__into_brass",
        "title": "Into the Brass Age",
        "desc": [
          "Craft or pick up a Brass Ingot - Create's mid-game alloy, and the trigger for Brass Age."
        ],
        "icon": "create:brass_ingot",
        "dependencies": [
          "andesite_age__iron_tools",
          "andesite_age__dumb_storage",
          "andesite_age__jetpack_1",
          "andesite_age__chunk_loader_1",
          "andesite_age__vein_hunting",
          "andesite_age__ars_wand"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "create:brass_ingot",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "item",
            "item": "numismatics:spur",
            "count": 4
          },
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 80
          }
        ]
      }
    ]
  },
  {
    "id": "brass_age",
    "title": "Brass Age",
    "subtitle": [
      "Automation begins in earnest."
    ],
    "icon": "create:brass_ingot",
    "order": 2,
    "quests": [
      {
        "id": "brass_age__enter",
        "title": "Enter the Brass Age",
        "desc": [
          "Automation begins in earnest. Diamond gear, the Nether, and a real powered storage network are all open now."
        ],
        "icon": "create:brass_ingot",
        "dependencies": [
          "andesite_age__into_brass"
        ],
        "tasks": [
          {
            "type": "gamestage",
            "stage": "brass_age"
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 150
          },
          {
            "type": "item",
            "item": "create:brass_ingot",
            "count": 1
          }
        ]
      },
      {
        "id": "brass_age__diamond_gear",
        "title": "Diamond Gear",
        "desc": [
          "Craft another Silent Gear pickaxe with Brass Age's material - the tool-tier milestone for this age."
        ],
        "icon": "minecraft:diamond_pickaxe",
        "dependencies": [
          "brass_age__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "silentgear:pickaxe",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 50
          },
          {
            "type": "item",
            "item": "numismatics:spur",
            "count": 4
          }
        ]
      },
      {
        "id": "brass_age__real_network",
        "title": "A Real Network",
        "desc": [
          "Craft a Refined Storage Controller - the heart of the powered network that replaces Tom's Storage from here on."
        ],
        "icon": "refinedstorage:controller",
        "dependencies": [
          "brass_age__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "refinedstorage:controller",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 50
          },
          {
            "type": "item",
            "item": "numismatics:spur",
            "count": 4
          }
        ]
      },
      {
        "id": "brass_age__alternator",
        "title": "Power the Network",
        "desc": [
          "Craft a Create Crafts & Additions Alternator - turns Create's own rotational power into the FE that runs Refined Storage."
        ],
        "icon": "createaddition:alternator",
        "dependencies": [
          "brass_age__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "createaddition:alternator",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 50
          },
          {
            "type": "item",
            "item": "numismatics:spur",
            "count": 4
          }
        ]
      },
      {
        "id": "brass_age__automation_arm",
        "title": "First Automation",
        "desc": [
          "Craft a Mechanical Arm - Create's own first crafting-automation block, feeding Refined Storage's Importer/Exporter."
        ],
        "icon": "create:mechanical_arm",
        "dependencies": [
          "brass_age__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "create:mechanical_arm",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 50
          },
          {
            "type": "item",
            "item": "numismatics:spur",
            "count": 4
          }
        ]
      },
      {
        "id": "brass_age__jetpack_2",
        "title": "Andesite Jetpack",
        "desc": [
          "Craft the Andesite Jetpack - fuel-fired propellers, rung 2 of the mobility ladder."
        ],
        "icon": "create_sa:andesite_jetpack_chestplate",
        "dependencies": [
          "brass_age__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "create_sa:andesite_jetpack_chestplate",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 50
          },
          {
            "type": "item",
            "item": "numismatics:spur",
            "count": 4
          }
        ]
      },
      {
        "id": "brass_age__chunk_loader_2",
        "title": "Brass Chunk Loader",
        "desc": [
          "Craft the Brass Chunk Loader - the second and final Power Loader rung."
        ],
        "icon": "create_power_loader:brass_chunk_loader",
        "dependencies": [
          "brass_age__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "create_power_loader:brass_chunk_loader",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 50
          },
          {
            "type": "item",
            "item": "numismatics:spur",
            "count": 4
          }
        ]
      },
      {
        "id": "brass_age__tiab",
        "title": "Time in a Bottle",
        "desc": [
          "Craft the Time in a Bottle tick accelerator - one per player, and it won't speed up spawners."
        ],
        "icon": "tiab:time_in_a_bottle",
        "dependencies": [
          "brass_age__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "tiab:time_in_a_bottle",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 50
          },
          {
            "type": "item",
            "item": "numismatics:spur",
            "count": 4
          }
        ]
      },
      {
        "id": "brass_age__trains",
        "title": "Train Control",
        "desc": [
          "Craft a Track Station - Create's own Trains are a full Brass Age package now."
        ],
        "icon": "create:track_station",
        "dependencies": [
          "brass_age__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "create:track_station",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 50
          },
          {
            "type": "item",
            "item": "numismatics:spur",
            "count": 4
          }
        ]
      },
      {
        "id": "brass_age__diet_upgrade",
        "title": "Sharper Knives",
        "desc": [
          "Craft a Farmer's Delight diamond knife - this is the real tier this pack's food-diet knife line reaches Brass Age (gold/diamond both unlock here; iron was Andesite Age, netherite is Precision Age)."
        ],
        "icon": "farmersdelight:diamond_knife",
        "dependencies": [
          "brass_age__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "farmersdelight:diamond_knife",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 50
          },
          {
            "type": "item",
            "item": "numismatics:spur",
            "count": 4
          }
        ]
      },
      {
        "id": "brass_age__master_alloy",
        "title": "The Master Alloy",
        "desc": [
          "Craft a Sturdy Sheet from Refined Radiance or Shadow Steel - Create's own top-tier alloy, and the door to Precision Age."
        ],
        "icon": "create:sturdy_sheet",
        "dependencies": [
          "brass_age__diamond_gear",
          "brass_age__real_network",
          "brass_age__alternator",
          "brass_age__automation_arm",
          "brass_age__jetpack_2",
          "brass_age__chunk_loader_2",
          "brass_age__tiab",
          "brass_age__trains",
          "brass_age__diet_upgrade"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "create:sturdy_sheet",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "item",
            "item": "numismatics:sprocket",
            "count": 1
          },
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 150
          }
        ]
      }
    ]
  },
  {
    "id": "precision_age",
    "title": "Precision Age",
    "subtitle": [
      "Create's own endgame alloys, and netherite gear."
    ],
    "icon": "create:sturdy_sheet",
    "order": 3,
    "quests": [
      {
        "id": "precision_age__enter",
        "title": "Enter the Precision Age",
        "desc": [
          "Create's own endgame alloys are done. Netherite gear and The End are open."
        ],
        "icon": "create:sturdy_sheet",
        "dependencies": [
          "brass_age__master_alloy"
        ],
        "tasks": [
          {
            "type": "gamestage",
            "stage": "precision_age"
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 300
          },
          {
            "type": "item",
            "item": "create:sturdy_sheet",
            "count": 1
          }
        ]
      },
      {
        "id": "precision_age__netherite_gear",
        "title": "Netherite Gear",
        "desc": [
          "Craft another Silent Gear pickaxe with Precision Age's material - the tool-tier milestone for this age."
        ],
        "icon": "minecraft:netherite_pickaxe",
        "dependencies": [
          "precision_age__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "silentgear:pickaxe",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 90
          },
          {
            "type": "item",
            "item": "numismatics:sprocket",
            "count": 1
          }
        ]
      },
      {
        "id": "precision_age__wireless",
        "title": "Cut the Cables",
        "desc": [
          "Craft a Wireless Grid - manage your Refined Storage network from anywhere in range."
        ],
        "icon": "refinedstorage:wireless_grid",
        "dependencies": [
          "precision_age__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "refinedstorage:wireless_grid",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 90
          },
          {
            "type": "item",
            "item": "numismatics:sprocket",
            "count": 1
          }
        ]
      },
      {
        "id": "precision_age__jetpack_3",
        "title": "Brass Jetpack",
        "desc": [
          "Craft the Brass Jetpack - steam-fired, rung 3 of the mobility ladder, and the base item the Induction Age netherite jetpack smiths from."
        ],
        "icon": "create_sa:brass_jetpack_chestplate",
        "dependencies": [
          "precision_age__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "create_sa:brass_jetpack_chestplate",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 90
          },
          {
            "type": "item",
            "item": "numismatics:sprocket",
            "count": 1
          }
        ]
      },
      {
        "id": "precision_age__elytra",
        "title": "Wings",
        "desc": [
          "Find an Elytra in an End City - it's not craftable, just gated behind reaching this tier and finding one."
        ],
        "icon": "minecraft:elytra",
        "dependencies": [
          "precision_age__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "minecraft:elytra",
            "count": 1,
            "consume": false,
            "onlyFromCrafting": false
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 90
          },
          {
            "type": "item",
            "item": "numismatics:sprocket",
            "count": 1
          }
        ]
      },
      {
        "id": "precision_age__diet_upgrade",
        "title": "The Netherite Knife",
        "desc": [
          "Craft a Farmer's Delight netherite knife (a smithing upgrade from the diamond knife) - the ceiling of this pack's food-diet knife line, keeping your bonus-hearts diet variety topped up through Precision Age's grind."
        ],
        "icon": "farmersdelight:netherite_knife",
        "dependencies": [
          "precision_age__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "farmersdelight:netherite_knife",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 90
          },
          {
            "type": "item",
            "item": "numismatics:sprocket",
            "count": 1
          }
        ]
      },
      {
        "id": "precision_age__vein_ceiling",
        "title": "The Netherite Drill",
        "desc": [
          "Craft the Netherite Drill - Create Ore Excavation's own tool ceiling, and what it takes to pull allthemodium/vibranium/unobtainium out of the ground."
        ],
        "icon": "createoreexcavation:netherite_drill",
        "dependencies": [
          "precision_age__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "createoreexcavation:netherite_drill",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 90
          },
          {
            "type": "item",
            "item": "numismatics:sprocket",
            "count": 1
          }
        ]
      },
      {
        "id": "precision_age__final_ingot",
        "title": "The Final Ingot",
        "desc": [
          "Craft or pick up a Netherite Ingot - the temporary trigger for Induction Age, until a real narrative trigger replaces it."
        ],
        "icon": "minecraft:netherite_ingot",
        "dependencies": [
          "precision_age__netherite_gear",
          "precision_age__wireless",
          "precision_age__jetpack_3",
          "precision_age__elytra",
          "precision_age__diet_upgrade",
          "precision_age__vein_ceiling"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "minecraft:netherite_ingot",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "item",
            "item": "numismatics:cog",
            "count": 1
          },
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 300
          }
        ]
      }
    ]
  },
  {
    "id": "induction_age",
    "title": "Induction Age",
    "subtitle": [
      "Full storage-network automation."
    ],
    "icon": "refinedstorage:advanced_processor",
    "order": 4,
    "quests": [
      {
        "id": "induction_age__enter",
        "title": "Enter the Induction Age",
        "desc": [
          "Full storage-network automation: 64k capacity and native pattern-based autocrafting are online."
        ],
        "icon": "minecraft:netherite_ingot",
        "dependencies": [
          "precision_age__final_ingot"
        ],
        "tasks": [
          {
            "type": "gamestage",
            "stage": "induction_age"
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 600
          },
          {
            "type": "item",
            "item": "minecraft:netherite_ingot",
            "count": 1
          }
        ]
      },
      {
        "id": "induction_age__autocrafting",
        "title": "Native Autocrafting",
        "desc": [
          "Craft an Autocrafting Upgrade - Refined Storage's own pattern-based autocrafter, no more Mechanical Arm needed for storage automation."
        ],
        "icon": "refinedstorage:autocrafting_upgrade",
        "dependencies": [
          "induction_age__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "refinedstorage:autocrafting_upgrade",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 150
          },
          {
            "type": "item",
            "item": "numismatics:cog",
            "count": 1
          }
        ]
      },
      {
        "id": "induction_age__storage_ceiling",
        "title": "64k Storage",
        "desc": [
          "Craft a 64k Storage Part - the ceiling of this pack's Refined Storage capacity chase (until the Jovian Frontier capstone)."
        ],
        "icon": "refinedstorage:64k_storage_part",
        "dependencies": [
          "induction_age__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "refinedstorage:64k_storage_part",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 150
          },
          {
            "type": "item",
            "item": "numismatics:cog",
            "count": 1
          }
        ]
      },
      {
        "id": "induction_age__jetpack_ceiling",
        "title": "Netherite Jetpack",
        "desc": [
          "Craft the Netherite Jetpack - the final rung before Starforged Age grants true persistent flight outright."
        ],
        "icon": "create_sa:netherite_jetpack_chestplate",
        "dependencies": [
          "induction_age__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "create_sa:netherite_jetpack_chestplate",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 150
          },
          {
            "type": "item",
            "item": "numismatics:cog",
            "count": 1
          }
        ]
      },
      {
        "id": "induction_age__teleport",
        "title": "Teleportation",
        "desc": [
          "Craft a Waystone - intra-world teleportation, gated all the way to this tier on purpose."
        ],
        "icon": "waystones:waystone",
        "dependencies": [
          "induction_age__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "waystones:waystone",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 150
          },
          {
            "type": "item",
            "item": "numismatics:cog",
            "count": 1
          }
        ]
      },
      {
        "id": "induction_age__steam_flight",
        "title": "Steam-Powered Flight",
        "desc": [
          "Craft a Steam Vent (Create Aeronautics) - the passive, industrial-scale heat source for sustained airship lift."
        ],
        "icon": "aeronautics:steam_vent",
        "dependencies": [
          "induction_age__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "aeronautics:steam_vent",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 150
          },
          {
            "type": "item",
            "item": "numismatics:cog",
            "count": 1
          }
        ]
      },
      {
        "id": "induction_age__gear_ceiling",
        "title": "Allthemodium",
        "desc": [
          "Smelt an Allthemodium Ingot - this pack's own post-netherite Silent Gear material floor, carrying gear progression into the space tiers."
        ],
        "icon": "allthemodium:allthemodium_ingot",
        "dependencies": [
          "induction_age__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "allthemodium:allthemodium_ingot",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 150
          },
          {
            "type": "item",
            "item": "numismatics:cog",
            "count": 1
          }
        ]
      },
      {
        "id": "induction_age__dragon",
        "title": "Conquer the End",
        "desc": [
          "Kill the Ender Dragon. The overworld, Nether, and End are done - this is the real trigger for Starforged Age."
        ],
        "icon": "minecraft:dragon_head",
        "dependencies": [
          "induction_age__autocrafting",
          "induction_age__storage_ceiling",
          "induction_age__jetpack_ceiling",
          "induction_age__teleport",
          "induction_age__steam_flight",
          "induction_age__gear_ceiling"
        ],
        "tasks": [
          {
            "type": "kill",
            "entity": "minecraft:ender_dragon",
            "count": 1
          }
        ],
        "rewards": [
          {
            "type": "item",
            "item": "numismatics:cog",
            "count": 4
          },
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 600
          }
        ]
      }
    ]
  },
  {
    "id": "starforged_age",
    "title": "Starforged Age",
    "subtitle": [
      "The overworld, Nether, and End are conquered. Space travel begins."
    ],
    "icon": "minecraft:nether_star",
    "order": 5,
    "quests": [
      {
        "id": "starforged_age__enter",
        "title": "Enter the Starforged Age",
        "desc": [
          "The overworld, Nether, and End are conquered. Space travel begins - and you can now toggle persistent flight outright."
        ],
        "icon": "minecraft:nether_star",
        "dependencies": [
          "induction_age__dragon"
        ],
        "tasks": [
          {
            "type": "gamestage",
            "stage": "starforged_age"
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 1200
          },
          {
            "type": "item",
            "item": "minecraft:nether_star",
            "count": 1
          }
        ]
      },
      {
        "id": "starforged_age__flight_ack",
        "title": "True Flight",
        "desc": [
          "Double-tap jump to toggle flight - it's granted the instant you reached this tier, no item or fuel required, and it survives death."
        ],
        "icon": "minecraft:elytra",
        "dependencies": [
          "starforged_age__enter"
        ],
        "tasks": [
          {
            "type": "checkmark"
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 100
          }
        ]
      },
      {
        "id": "starforged_age__leaderboard_check",
        "title": "Check Your Rank (optional)",
        "desc": [
          "Run /leaderboard wealth, /leaderboard tier, or /leaderboard level to see how you and your team stack up."
        ],
        "icon": "numismatics:sun",
        "dependencies": [
          "starforged_age__enter"
        ],
        "tasks": [
          {
            "type": "checkmark"
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 100
          }
        ]
      },
      {
        "id": "starforged_age__aluminum_age",
        "title": "The Aluminum Age",
        "desc": [
          "Smelt a TFMG Aluminum Ingot - the first rung of the endgame automation ladder that carries all the way to Jupiter."
        ],
        "icon": "tfmg:aluminum_ingot",
        "dependencies": [
          "starforged_age__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "tfmg:aluminum_ingot",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 100
          },
          {
            "type": "item",
            "item": "numismatics:cog",
            "count": 4
          }
        ]
      },
      {
        "id": "starforged_age__rocket_parts",
        "title": "Rocket Parts",
        "desc": [
          "Craft a Rocket Engine (Stellaris) - one of the core components of your first rocket."
        ],
        "icon": "stellaris:rocket_engine",
        "dependencies": [
          "starforged_age__aluminum_age"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "stellaris:rocket_engine",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 100
          },
          {
            "type": "item",
            "item": "numismatics:cog",
            "count": 4
          }
        ]
      },
      {
        "id": "starforged_age__launch",
        "title": "Liftoff",
        "desc": [
          "Launch your rocket and reach Earth orbit - the real trigger for Lunar Frontier."
        ],
        "icon": "stellaris:rocket",
        "dependencies": [
          "starforged_age__rocket_parts"
        ],
        "tasks": [
          {
            "type": "dimension",
            "dimension": "stellaris:earth_orbit"
          }
        ],
        "rewards": [
          {
            "type": "item",
            "item": "numismatics:crown",
            "count": 2
          },
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 1200
          }
        ]
      }
    ]
  },
  {
    "id": "lunar_frontier",
    "title": "Lunar Frontier",
    "subtitle": [
      "You've reached orbit. The Moon is next."
    ],
    "icon": "stellaris:rocket",
    "order": 6,
    "quests": [
      {
        "id": "lunar_frontier__enter",
        "title": "Enter the Lunar Frontier",
        "desc": [
          "You've reached orbit. The Moon is next."
        ],
        "icon": "stellaris:rocket",
        "dependencies": [
          "starforged_age__launch"
        ],
        "tasks": [
          {
            "type": "gamestage",
            "stage": "lunar_frontier"
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 1500
          },
          {
            "type": "item",
            "item": "allthemodium:unobtainium_ingot",
            "count": 1
          }
        ]
      },
      {
        "id": "lunar_frontier__steel_age",
        "title": "The Steel Age",
        "desc": [
          "Smelt a TFMG Steel Ingot - the mod's own core metallurgy chain, rung 2 of the endgame automation ladder."
        ],
        "icon": "tfmg:steel_ingot",
        "dependencies": [
          "lunar_frontier__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "tfmg:steel_ingot",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 150
          },
          {
            "type": "item",
            "item": "numismatics:cog",
            "count": 4
          }
        ]
      },
      {
        "id": "lunar_frontier__moon_landing",
        "title": "One Small Step",
        "desc": [
          "Travel to the Moon - the real trigger for Martian Frontier."
        ],
        "icon": "minecraft:end_crystal",
        "dependencies": [
          "lunar_frontier__steel_age"
        ],
        "tasks": [
          {
            "type": "dimension",
            "dimension": "stellaris:moon"
          }
        ],
        "rewards": [
          {
            "type": "item",
            "item": "numismatics:crown",
            "count": 2
          },
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 1500
          }
        ]
      }
    ]
  },
  {
    "id": "martian_frontier",
    "title": "Martian Frontier",
    "subtitle": [
      "The Moon is conquered. Mars is next."
    ],
    "icon": "minecraft:redstone",
    "order": 7,
    "quests": [
      {
        "id": "martian_frontier__enter",
        "title": "Enter the Martian Frontier",
        "desc": [
          "The Moon is conquered. Mars is next."
        ],
        "icon": "minecraft:redstone",
        "dependencies": [
          "lunar_frontier__moon_landing"
        ],
        "tasks": [
          {
            "type": "gamestage",
            "stage": "martian_frontier"
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 1800
          },
          {
            "type": "item",
            "item": "tfmg:diesel_bucket",
            "count": 1
          }
        ]
      },
      {
        "id": "martian_frontier__petrochemical",
        "title": "The Petrochemical Age",
        "desc": [
          "Refine a bucket of Diesel (TFMG) - rung 3 of the endgame automation ladder."
        ],
        "icon": "tfmg:diesel_bucket",
        "dependencies": [
          "martian_frontier__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "tfmg:diesel_bucket",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 180
          },
          {
            "type": "item",
            "item": "numismatics:cog",
            "count": 5
          }
        ]
      },
      {
        "id": "martian_frontier__mars_landing",
        "title": "Red Planet",
        "desc": [
          "Travel to Mars - the real trigger for Inner System."
        ],
        "icon": "minecraft:redstone_block",
        "dependencies": [
          "martian_frontier__petrochemical"
        ],
        "tasks": [
          {
            "type": "dimension",
            "dimension": "stellaris:mars"
          }
        ],
        "rewards": [
          {
            "type": "item",
            "item": "numismatics:crown",
            "count": 2
          },
          {
            "type": "item",
            "item": "numismatics:cog",
            "count": 2
          },
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 1800
          }
        ]
      }
    ]
  },
  {
    "id": "inner_system",
    "title": "Inner System",
    "subtitle": [
      "Mars is conquered. Venus and Mercury are next."
    ],
    "icon": "minecraft:magma_block",
    "order": 8,
    "quests": [
      {
        "id": "inner_system__enter",
        "title": "Enter the Inner System",
        "desc": [
          "Mars is conquered. Venus and Mercury - both extreme, comparably hostile - are next."
        ],
        "icon": "minecraft:magma_block",
        "dependencies": [
          "martian_frontier__mars_landing"
        ],
        "tasks": [
          {
            "type": "gamestage",
            "stage": "inner_system"
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 2100
          },
          {
            "type": "item",
            "item": "tfmg:electric_motor",
            "count": 1
          }
        ]
      },
      {
        "id": "inner_system__electrical_age",
        "title": "The Electrical Age",
        "desc": [
          "Craft a TFMG Converter - bridges TFMG's own power grid into Create/FE, rung 4 of the endgame automation ladder."
        ],
        "icon": "tfmg:converter",
        "dependencies": [
          "inner_system__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "tfmg:converter",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 200
          },
          {
            "type": "item",
            "item": "numismatics:cog",
            "count": 6
          }
        ]
      },
      {
        "id": "inner_system__venus_landing",
        "title": "Morning Star (optional)",
        "desc": [
          "Travel to Venus - either inner planet triggers Jovian Frontier, so this and Mercury are both optional."
        ],
        "icon": "minecraft:magma_block",
        "dependencies": [
          "inner_system__electrical_age"
        ],
        "tasks": [
          {
            "type": "dimension",
            "dimension": "stellaris:venus"
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 200
          },
          {
            "type": "item",
            "item": "numismatics:cog",
            "count": 6
          }
        ]
      },
      {
        "id": "inner_system__mercury_landing",
        "title": "Swift Planet (optional)",
        "desc": [
          "Travel to Mercury - either inner planet triggers Jovian Frontier, so this and Venus are both optional."
        ],
        "icon": "minecraft:magma_block",
        "dependencies": [
          "inner_system__electrical_age"
        ],
        "tasks": [
          {
            "type": "dimension",
            "dimension": "stellaris:mercury"
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 200
          },
          {
            "type": "item",
            "item": "numismatics:cog",
            "count": 6
          }
        ]
      }
    ]
  },
  {
    "id": "jovian_frontier",
    "title": "Jovian Frontier",
    "subtitle": [
      "The inner system is conquered. Jupiter is the final frontier."
    ],
    "icon": "minecraft:end_crystal",
    "order": 9,
    "quests": [
      {
        "id": "jovian_frontier__enter",
        "title": "Enter the Jovian Frontier",
        "desc": [
          "The inner system is conquered. Jupiter - the current edge of Stellaris' explorable system - is the final frontier."
        ],
        "icon": "minecraft:end_crystal",
        "dependencies": [
          "inner_system__electrical_age"
        ],
        "tasks": [
          {
            "type": "gamestage",
            "stage": "jovian_frontier"
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 2400
          },
          {
            "type": "item",
            "item": "allthemodium:unobtainium_vibranium_alloy_ingot",
            "count": 1
          }
        ]
      },
      {
        "id": "jovian_frontier__combustion_age",
        "title": "The Combustion Age",
        "desc": [
          "Craft a TFMG Engine Cylinder - the final rung of the endgame automation ladder."
        ],
        "icon": "tfmg:engine_cylinder",
        "dependencies": [
          "jovian_frontier__enter"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "tfmg:engine_cylinder",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 250
          },
          {
            "type": "item",
            "item": "numismatics:cog",
            "count": 7
          }
        ]
      },
      {
        "id": "jovian_frontier__storage_infinity",
        "title": "Infinite Storage",
        "desc": [
          "Craft a Refined Storage Creative Storage Block - genuinely infinite item capacity, the true ceiling of the storage chase started back at Andesite Age."
        ],
        "icon": "refinedstorage:creative_storage_block",
        "dependencies": [
          "jovian_frontier__combustion_age"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "refinedstorage:creative_storage_block",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 300
          },
          {
            "type": "item",
            "item": "numismatics:cog",
            "count": 7
          }
        ]
      },
      {
        "id": "jovian_frontier__energy_infinity",
        "title": "Infinite Energy",
        "desc": [
          "Craft a Create Creative Motor - a genuinely endless source of Rotational Force, bridged to FE the same way every earlier power step in this pack has been."
        ],
        "icon": "create:creative_motor",
        "dependencies": [
          "jovian_frontier__combustion_age"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "create:creative_motor",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 300
          },
          {
            "type": "item",
            "item": "numismatics:cog",
            "count": 7
          }
        ]
      },
      {
        "id": "jovian_frontier__resource_infinity",
        "title": "Infinite Resources",
        "desc": [
          "Craft a Create Creative Crate - an endless supply of any one item you configure. This is the hardest, latest-gated craft in the entire pack for a reason - guard it accordingly."
        ],
        "icon": "create:creative_crate",
        "dependencies": [
          "jovian_frontier__combustion_age"
        ],
        "tasks": [
          {
            "type": "item",
            "item": "create:creative_crate",
            "count": 1,
            "consume": true,
            "onlyFromCrafting": true
          }
        ],
        "rewards": [
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 300
          },
          {
            "type": "item",
            "item": "numismatics:cog",
            "count": 7
          }
        ]
      },
      {
        "id": "jovian_frontier__journeys_end",
        "title": "Journey's End",
        "desc": [
          "Every tier from Rootborn to Jupiter, done. Future updates may extend the ladder further out into the solar system - this book will grow to meet them."
        ],
        "icon": "minecraft:nether_star",
        "dependencies": [
          "jovian_frontier__storage_infinity",
          "jovian_frontier__energy_infinity",
          "jovian_frontier__resource_infinity"
        ],
        "tasks": [
          {
            "type": "checkmark"
          }
        ],
        "rewards": [
          {
            "type": "item",
            "item": "numismatics:crown",
            "count": 3
          },
          {
            "type": "xp",
            "category": "adventurer",
            "amount": 2400
          }
        ]
      }
    ]
  }
]

// ---------------------------------------------------------------------------
// Runtime: bespoke quest tracker (GitHub #33), replacing FTB Quests.
//
// Team-shared PROGRESS, per-player REWARDS (instructions.md line 41: "Players
// should share progress (but not rewards) for preset track quests" - this IS
// the preset track, formerly FTB Quests' "Tier Progression" chapter). Quest
// completion is stored keyed by getProgressKey(player) below (a team/party id
// when the player is in a real multi-member party, else a per-player key) -
// so any teammate satisfying a quest's tasks marks it done for the whole
// team, unlocking dependents for everyone - but the reward grant (items/xp/
// commands) goes ONLY to the player whose live state the tick scan (or
// /quest check) actually found satisfying, never broadcast to teammates.
//
// PARTY-ID SEAM for GitHub #32 (Open Parties and Claims, replacing FTB
// Teams) - LANDED, integrated alongside #33 at merge time. getProgressKey()
// below was written as the ONE function that seam needed to change - every
// other function in this file keys exclusively off the string it returns,
// so this was a one-function edit, not a redesign, exactly as planned.
// Ground truth for the OPAC-based lookup, confirmed by reading the real
// interface source (decompiled from the actually-resolved
// open-parties-and-claims-neoforge-1.21.1-0.27.8.jar's Modrinth-published
// sources jar, xaero.pac.common.server.parties.party.api package):
// xaero.pac.common.server.api.OpenPACServerAPI.get(server) -> instance;
// .getPartyManager() -> IPartyManagerAPI; .getPartyByMember(UUID) ->
// IServerPartyAPI (@Nullable, null if the player has no party) - a direct
// player->party lookup, unlike the getAllStream()-based aggregation
// leaderboard.js's collectTeamEntries()/progression_stage_bridge.js's
// psbSyncPartyStages use (those iterate every party for a different
// purpose - building a full leaderboard / syncing every party's members -
// this just needs one player's own party). IServerPartyAPI.getId() -> UUID
// is the progress key. OPAC does NOT auto-create a solo party per player
// the way FTB Teams did, so a solo player's lookup returns null and falls
// through to the per-player key below, same as before.
//
// Task checking: item tasks are a live inventory-count check (same
// container-scanning shape as leaderboard.js's countCoins(), generalized to
// any item id) with optional consume-on-complete - NOT an FTB-Quests-style
// "must have been freshly crafted" event tracker (see gen_quests.py's own
// docstring for why this simplification is deliberate and precedented by
// progression_stage_bridge.js's GitHub #23 fix). Kill tasks read the
// vanilla per-entity-type kill stat directly (dev.latvian.mods.kubejs.
// player.PlayerStatsJS.getKilled(EntityType<?>) - confirmed via javap
// against the installed kubejs jar; net.minecraft.world.entity.EntityType.
// byString(String) resolves the configured entity id to the EntityType
// instance that method needs, confirmed via javap against the installed
// server jar's SRG-named class dump under net/minecraft/world/entity/
// EntityType.class). Dimension tasks compare String(player.level.dimension)
// against the configured dimension id (same accessor mob_scaling.js already
// uses for DIMENSION_FACTOR lookups). Gamestage tasks read player.stages.has
// (id) (same binding leaderboard.js/progression_stage_bridge.js/selftest.js
// already use). Checkmark tasks are never tick-completed - they require the
// player to run /quest check <id> themselves, since there is no self-check
// GUI to click in a chat-command-only redesign.

const QuestsCompoundTagClass = Java.loadClass('net.minecraft.nbt.CompoundTag')
const QuestsEntityTypeClass = Java.loadClass('net.minecraft.world.entity.EntityType')

let QuestsOpenPACServerAPIClass = null
try {
    QuestsOpenPACServerAPIClass = Java.loadClass('xaero.pac.common.server.api.OpenPACServerAPI')
} catch (e) {
    console.error('[vpp quests] Open Parties and Claims API (xaero.pac.common.server.api.OpenPACServerAPI) failed to load - quest progress will always be per-player: ' + e)
}

// ---- progress-key seam (see header comment - the one function GitHub #32 needed to change) ----

function getProgressKey(player) {
    if (QuestsOpenPACServerAPIClass) {
        try {
            let partyManager = QuestsOpenPACServerAPIClass.get(player.server).getPartyManager()
            let party = partyManager.getPartyByMember(player.uuid)
            if (party) {
                return 'team:' + party.getId()
            }
        } catch (e) {
            console.error('[vpp quests] party lookup failed for ' + player.username + ', falling back to a per-player key: ' + e)
        }
    }
    return 'player:' + player.uuid
}

// ---- persistent progress storage (server.persistentData, same pattern leaderboard.js's cache uses) ----

function questsEnsureCompound(parent, key) {
    if (!parent.contains(key, 10)) { // 10 = NBT compound-tag type id
        parent.put(key, new QuestsCompoundTagClass())
    }
    return parent.getCompound(key)
}

const QUESTS_PROGRESS_ROOT_KEY = 'vpp_quests_progress'

function questsProgressCompound(server, progressKey) {
    let root = questsEnsureCompound(server.persistentData, QUESTS_PROGRESS_ROOT_KEY)
    return questsEnsureCompound(root, progressKey)
}

function isQuestComplete(server, progressKey, questId) {
    return questsProgressCompound(server, progressKey).getBoolean(questId)
}

function markQuestComplete(server, progressKey, questId) {
    questsProgressCompound(server, progressKey).putBoolean(questId, true)
}

function dependenciesSatisfied(server, progressKey, quest) {
    for (let i = 0; i < quest.dependencies.length; i++) {
        if (!isQuestComplete(server, progressKey, quest.dependencies[i])) return false
    }
    return true
}

function hasCheckmarkTask(quest) {
    for (let i = 0; i < quest.tasks.length; i++) {
        if (quest.tasks[i].type === 'checkmark') return true
    }
    return false
}

// ---- task checking ----

function questsCountItem(player, itemId) {
    let total = 0
    let inv = player.getInventory()
    let size = inv.getContainerSize()
    for (let i = 0; i < size; i++) {
        let stack = inv.getItem(i)
        if (!stack || stack.isEmpty()) continue
        if (stack.id === itemId) total += stack.getCount()
    }
    return total
}

function questsConsumeItem(player, itemId, count) {
    let remaining = count
    let inv = player.getInventory()
    let size = inv.getContainerSize()
    for (let i = 0; i < size && remaining > 0; i++) {
        let stack = inv.getItem(i)
        if (!stack || stack.isEmpty() || stack.id !== itemId) continue
        let take = Math.min(remaining, stack.getCount())
        stack.setCount(stack.getCount() - take)
        remaining -= take
    }
}

function checkTask(player, task) {
    switch (task.type) {
        case 'item':
            return questsCountItem(player, task.item) >= task.count
        case 'kill': {
            let opt = QuestsEntityTypeClass.byString(task.entity)
            if (!opt.isPresent()) return false
            return player.stats.getKilled(opt.get()) >= task.count
        }
        case 'dimension':
            return String(player.level.dimension) === task.dimension
        case 'gamestage':
            return player.stages.has(task.stage)
        case 'checkmark':
            return false // player-invoked only, via /quest check
        default:
            console.error('[vpp quests] unknown task type: ' + task.type)
            return false
    }
}

function questSatisfied(player, quest) {
    for (let i = 0; i < quest.tasks.length; i++) {
        if (!checkTask(player, quest.tasks[i])) return false
    }
    return true
}

// ---- rewards (same COINS/payCoins convention as economy.js) ----

const QUESTS_COINS = [
    ['numismatics:sun', 4096], ['numismatics:crown', 512], ['numismatics:cog', 64],
    ['numismatics:sprocket', 16], ['numismatics:bevel', 8], ['numismatics:spur', 1],
]

function applyReward(player, reward) {
    switch (reward.type) {
        case 'item':
            player.give(Item.of(reward.item, reward.count))
            break
        case 'xp':
            player.server.runCommandSilent(`puffish_skills experience add ${player.username} ${reward.category} ${reward.amount}`)
            break
        case 'command':
            player.server.runCommandSilent(reward.command.split('{p}').join(player.username))
            break
        case 'gamestage':
            player.stages.add(reward.stage)
            break
        case 'toast':
            player.tell(`*** ${reward.message} ***`)
            break
        default:
            console.error('[vpp quests] unknown reward type: ' + reward.type)
    }
}

function grantRewards(player, quest) {
    for (let i = 0; i < quest.rewards.length; i++) {
        try {
            applyReward(player, quest.rewards[i])
        } catch (e) {
            console.error('[vpp quests] reward grant failed for ' + player.username + ' on quest ' + quest.id + ': ' + e)
        }
    }
}

function notifyTeammates(server, progressKey, completer, quest) {
    for (const p of server.players) { // KubeJS EntityArrayList, proven for-of target (mob_scaling.js/leaderboard.js)
        if (String(p.uuid) === String(completer.uuid)) continue
        if (getProgressKey(p) === progressKey) {
            p.tell(`Team quest complete: ${quest.title} (completed by ${completer.username})`)
        }
    }
}

// ---- GitHub #36: vanilla advancement tree, granted via command (the
// advancements themselves use a minecraft:impossible criterion - see
// scripts/gen_quests.py's write_advancements() - so this command is the
// ONLY way any of them are ever granted). Re-granting an already-held
// advancement is a harmless vanilla no-op, so none of the call sites below
// need to check possession first. ----

function grantAdvancement(player, questId) {
    try {
        player.server.runCommandSilent(`advancement grant ${player.username} only vanillaplusplus:quests/${questId}`)
    } catch (e) {
        console.error('[vpp quests] advancement grant failed for ' + player.username + ' on quest ' + questId + ': ' + e)
    }
}

// The advancement is a visual mirror of team-shared PROGRESS (same sharing
// model as quest completion itself), not of per-player REWARDS - granted to
// every online teammate, not just whichever player's live state actually
// satisfied the task.
function grantAdvancementToTeam(server, progressKey, quest) {
    for (const p of server.players) {
        if (getProgressKey(p) === progressKey) grantAdvancement(p, quest.id)
    }
}

function completeQuest(server, player, progressKey, quest) {
    for (let i = 0; i < quest.tasks.length; i++) {
        let task = quest.tasks[i]
        if (task.type === 'item' && task.consume) questsConsumeItem(player, task.item, task.count)
    }
    markQuestComplete(server, progressKey, quest.id)
    grantRewards(player, quest)
    player.tell(`Quest complete: ${quest.title}`)
    notifyTeammates(server, progressKey, player, quest)
    grantAdvancementToTeam(server, progressKey, quest)
}

// Catch-up sync on login: a player who joins a party mid-progress, or just
// reconnects, gets every already-completed team quest's advancement
// granted silently - no reward re-grant (rewards were already handled at
// original completion time), no chat spam, just the visual layer catching
// up. Same event hook leaderboard.js already uses for loggedOut.
PlayerEvents.loggedIn(event => {
    let player = event.player
    if (!player || !player.server) return
    try {
        let server = player.server
        let progressKey = getProgressKey(player)
        for (const questId of Object.keys(QUEST_BY_ID)) {
            if (isQuestComplete(server, progressKey, questId)) grantAdvancement(player, questId)
        }
    } catch (e) {
        console.error('[vpp quests] login advancement catch-up failed for ' + player.username + ': ' + e)
    }
})

// ---- tick scan ----

const QUESTS_TICK_INTERVAL = 100 // 5s, matches achievements.js's own cadence

let questsTickCounter = 0
ServerEvents.tick(event => {
    questsTickCounter++
    if (questsTickCounter % QUESTS_TICK_INTERVAL !== 0) return

    for (const player of event.server.players) {
        try {
            scanQuestsForPlayer(player)
        } catch (e) {
            console.error('[vpp quests] tick scan failed for ' + player.username + ': ' + e)
        }
    }
})

function scanQuestsForPlayer(player) {
    let server = player.server
    let progressKey = getProgressKey(player)
    for (const chapter of QUEST_CHAPTERS) {
        for (const quest of chapter.quests) {
            if (hasCheckmarkTask(quest)) continue
            if (isQuestComplete(server, progressKey, quest.id)) continue
            if (!dependenciesSatisfied(server, progressKey, quest)) continue
            if (!questSatisfied(player, quest)) continue
            completeQuest(server, player, progressKey, quest)
        }
    }
}

// ---- flattened lookups ----

const QUEST_BY_ID = {}
const CHECKMARK_QUEST_IDS = []
for (const chapter of QUEST_CHAPTERS) {
    for (const quest of chapter.quests) {
        QUEST_BY_ID[quest.id] = quest
        if (hasCheckmarkTask(quest)) CHECKMARK_QUEST_IDS.push(quest.id)
    }
}

// ---- manual checkmark completion ----

function runCheckmarkCheck(player, questId) {
    let server = player.server
    let quest = QUEST_BY_ID[questId]
    if (!quest) { player.tell('Unknown quest id: ' + questId); return }
    let progressKey = getProgressKey(player)
    if (isQuestComplete(server, progressKey, questId)) {
        player.tell(`Already complete: ${quest.title}`)
        return
    }
    if (!dependenciesSatisfied(server, progressKey, quest)) {
        player.tell(`Locked - complete its prerequisites first: ${quest.title}`)
        return
    }
    completeQuest(server, player, progressKey, quest)
}

// ---- describe helpers for /quests <chapter> ----

function describeTask(task) {
    switch (task.type) {
        case 'item':
            return `${task.consume ? 'Turn in' : 'Have'} ${task.count}x ${task.item}` + (task.onlyFromCrafting ? ' (crafted)' : '')
        case 'kill':
            return `Kill ${task.count}x ${task.entity}`
        case 'dimension':
            return `Travel to ${task.dimension}`
        case 'gamestage':
            return `Reach stage: ${task.stage}`
        case 'checkmark':
            return 'Self-check (/quest check ' + '<id>)'
        default:
            return task.type
    }
}

function describeReward(reward) {
    switch (reward.type) {
        case 'item':
            return `${reward.count}x ${reward.item}`
        case 'xp':
            return `${reward.amount} ${reward.category} XP`
        case 'command':
            return 'command reward'
        case 'gamestage':
            return `stage: ${reward.stage}`
        case 'toast':
            return 'announcement'
        default:
            return reward.type
    }
}

function describeTasks(quest) {
    return quest.tasks.map(describeTask).join('; ')
}

function describeRewards(quest) {
    return quest.rewards.map(describeReward).join(', ')
}

// ---- chat command family ----

function showQuestsOverview(player) {
    let server = player.server
    let progressKey = getProgressKey(player)
    player.tell('--- Quests ---')
    let current = null
    for (const chapter of QUEST_CHAPTERS) {
        let total = chapter.quests.length
        let done = chapter.quests.filter(q => isQuestComplete(server, progressKey, q.id)).length
        player.tell(`${chapter.title}: ${done}/${total}`)
        if (!current && done < total) current = chapter
    }
    if (!current) current = QUEST_CHAPTERS[QUEST_CHAPTERS.length - 1]
    player.tell(`Current chapter: ${current.title} - run /quests ${current.id} for details.`)
}

function showChapterDetail(player, chapter) {
    let server = player.server
    let progressKey = getProgressKey(player)
    player.tell(`--- ${chapter.title} ---`)
    for (const line of chapter.subtitle) player.tell(line)
    for (const quest of chapter.quests) {
        let complete = isQuestComplete(server, progressKey, quest.id)
        let locked = !complete && !dependenciesSatisfied(server, progressKey, quest)
        let status = complete ? 'DONE' : (locked ? 'LOCKED' : 'OPEN')
        player.tell(`[${status}] ${quest.title} - ${describeTasks(quest)} -> ${describeRewards(quest)}`)
    }
}

ServerEvents.commandRegistry(event => {
    const { commands: Commands } = event

    // /quests [chapter] - one literal subcommand per chapter id (10, a
    // small fixed set), NOT a Commands.argument(...)/Arguments.STRING
    // interop call - same reasoning skill_respec.js's own /respec command
    // already documented: no script in this pack has ever registered a
    // string ArgumentType and this cannot be boot-tested here to find out
    // if that guess would be right, so literal chaining (already proven
    // via economy.js/dailies.js/leaderboard.js) is used throughout instead.
    let questsCmd = Commands.literal('quests')
        .executes(ctx => { showQuestsOverview(ctx.source.playerOrException); return 1 })
    for (const chapter of QUEST_CHAPTERS) {
        questsCmd = questsCmd.then(
            Commands.literal(chapter.id).executes(ctx => {
                showChapterDetail(ctx.source.playerOrException, chapter)
                return 1
            })
        )
    }
    event.register(questsCmd)

    // /quest check <id> - one literal subcommand per checkmark quest (a
    // small fixed set - 4 in this book's actual content), same reasoning.
    let checkCmd = Commands.literal('check')
        .executes(ctx => {
            ctx.source.playerOrException.tell('Usage: /quest check <id>. Checkmark quests: ' + CHECKMARK_QUEST_IDS.join(', '))
            return 0
        })
    for (const qid of CHECKMARK_QUEST_IDS) {
        checkCmd = checkCmd.then(
            Commands.literal(qid).executes(ctx => {
                runCheckmarkCheck(ctx.source.playerOrException, qid)
                return 1
            })
        )
    }
    event.register(Commands.literal('quest').then(checkCmd))
})
