// Item 11 (skill-tree overhaul, DECISIONS.md) - `/respec <category>`.
//
// Every one of the 12 puffish_skills categories generated by
// scripts/gen_skill_tree.py now forks at its 5-node shared trunk into two
// mutually-exclusive 5-node spec paths (nodes a0-a4 / b0-b4), enforced
// natively by a single `exclusive.bidirectional` connection between the two
// fork-entry nodes (a0<->b0) - see that script's gen_category docstring for
// the schema this depends on, verified via javap against the real
// puffish_skills-0.18.0 jar this session.
//
// CORRECTNESS GOTCHA (also javap-verified this session, against
// net.puffish.skillsmod.server.data.CategoryData.getSkillState): a skill
// that is already unlocked reports UNLOCKED unconditionally - that check
// runs BEFORE the exclusion check, so a node never gets silently un-unlocked
// or un-rewarded just because its exclusive counterpart got picked. Locking
// is the only thing that removes a node's reward. That means a respec MUST
// explicitly .lock() every one of the 5 nodes on the abandoned path, not
// just the fork-entry node - locking only a0 (say) would flip b0 out of
// EXCLUDED and make it choosable again, but a1-a4 would stay unlocked and
// silently keep granting their rewards forever (orphaned, unreachable via
// the tree UI, un-refunded). This file's respecCategory() loops all 5.
//
// API surface (javap-verified against net.puffish.skillsmod.api.* in the
// same jar):
//   SkillsAPI.getCategory(ResourceLocation) -> Optional<Category>
//   Category.getSkill(String id)            -> Optional<Skill>
//   Skill.getState(ServerPlayer)            -> Skill$State enum
//   Skill.lock(ServerPlayer)                -> void (delegates to
//     SkillsMod.lockSkill, the same server-side entrypoint the mod's own
//     skill-tree screen uses to refund a node - spent points are computed
//     live from the unlocked-skill set, so refund is automatic, no manual
//     point bookkeeping needed here)
// Skill$State is compared by string (`String(skill.getState(player))`)
// rather than loading the nested Skill$State class and comparing enum
// constants - avoids depending on Rhino's handling of a `Class$Name`
// nested-class load (unverified in this codebase; no existing script here
// loads a nested class) for a check that a plain string equality already
// covers safely. Everything else follows the Java.loadClass-with-try/catch
// + ResourceLocation.fromNamespaceAndPath house style already established in
// leaderboard.js/selftest.js, since - like those two - this cannot be
// boot-tested in this sandbox (no server, no client).

const RESPEC_SKILL_CATEGORIES = [
    'bows', 'building', 'daggers', 'greatswords', 'longswords', 'magic',
    'mining', 'running', 'spears', 'swimming', 'swords', 'tachi',
]

let RespecResourceLocationClass = null
let RespecSkillsAPIClass = null
try {
    RespecResourceLocationClass = Java.loadClass('net.minecraft.resources.ResourceLocation')
    RespecSkillsAPIClass = Java.loadClass('net.puffish.skillsmod.api.SkillsAPI')
} catch (e) {
    console.error('[vpp respec] Pufferfish Skills API failed to load - /respec will be unavailable: ' + e)
}

// ---------------------------------------------------------------------------
// Cost hook. Respec is FREE for now (provisional call, recorded in
// DECISIONS.md - open balance question for playtest). This is the one
// obvious insertion point for a future cost: return false (after telling the
// player why, e.g. insufficient currency) to block the respec, or charge the
// currency here and return true to let it proceed.
// ---------------------------------------------------------------------------
function chargeRespecCost(player, categoryId) {
    return true
}

// Which fork the player has committed to for this category, 'a' | 'b' | null
// (null = trunk-only so far, nothing to respec).
function findCommittedPath(category, player) {
    const aOpt = category.getSkill('a0')
    if (aOpt.isPresent() && String(aOpt.get().getState(player)) === 'UNLOCKED') return 'a'
    const bOpt = category.getSkill('b0')
    if (bOpt.isPresent() && String(bOpt.get().getState(player)) === 'UNLOCKED') return 'b'
    return null
}

function respecCategory(player, categoryId) {
    if (!RespecSkillsAPIClass || !RespecResourceLocationClass) {
        player.tell('Respec is unavailable right now (skill API failed to load).')
        return
    }
    try {
        const rl = RespecResourceLocationClass.fromNamespaceAndPath('puffish_skills', categoryId)
        const catOpt = RespecSkillsAPIClass.getCategory(rl)
        if (!catOpt.isPresent()) {
            player.tell(`Unknown skill category: ${categoryId}`)
            return
        }
        const category = catOpt.get()

        const path = findCommittedPath(category, player)
        if (!path) {
            player.tell(`You haven't committed to a spec path in ${categoryId} yet - nothing to respec.`)
            return
        }

        if (!chargeRespecCost(player, categoryId)) {
            return // chargeRespecCost is responsible for telling the player why
        }

        const nodeIds = [0, 1, 2, 3, 4].map(i => path + i) // ['a0'..'a4'] or ['b0'..'b4']
        let lockedCount = 0
        for (const nodeId of nodeIds) {
            try {
                const skillOpt = category.getSkill(nodeId)
                if (!skillOpt.isPresent()) {
                    console.error(`[vpp respec] ${categoryId}/${nodeId} missing from category config - skipped`)
                    continue
                }
                const skill = skillOpt.get()
                if (String(skill.getState(player)) === 'UNLOCKED') {
                    skill.lock(player)
                    lockedCount++
                }
            } catch (e) {
                console.error(`[vpp respec] failed to lock ${categoryId}/${nodeId} for ${player.username}: ${e}`)
            }
        }

        const pathLabel = path === 'a' ? 'A' : 'B'
        player.tell(`Respec complete: cleared ${lockedCount} node(s) on the ${pathLabel} path of ${categoryId}. Points refunded - both paths are open again.`)
    } catch (e) {
        console.error(`[vpp respec] respec failed for ${player.username} / ${categoryId}: ${e}`)
        player.tell('Respec failed - see server log.')
    }
}

ServerEvents.commandRegistry(event => {
    const { commands: Commands } = event

    let respecCommand = Commands.literal('respec')
        .executes(ctx => {
            ctx.source.playerOrException.tell(`Usage: /respec <category>. Categories: ${RESPEC_SKILL_CATEGORIES.join(', ')}`)
            return 0
        })

    // One literal subcommand per category rather than a string ArgumentType
    // - Brigadier literal chaining (Commands.literal(...).then(...)) is
    // already exercised elsewhere in this pack's command registrations
    // (economy.js/dailies.js), whereas no script here has ever registered a
    // Commands.argument(...)/Arguments.STRING interop call, and this cannot
    // be boot-tested to find out if that guess would have been right.
    for (const categoryId of RESPEC_SKILL_CATEGORIES) {
        respecCommand = respecCommand.then(
            Commands.literal(categoryId)
                .executes(ctx => {
                    respecCategory(ctx.source.playerOrException, categoryId)
                    return 1
                })
        )
    }

    event.register(respecCommand)
})
