// GENERATED by scripts/gen_weapon_tiers.py - do not hand-edit, re-run the script instead.
// Gear overhaul Part 5: boss-unique weapons. Loot-only, no smithing recipe -
// see data/minecraft/loot_table/entities/{wither,ender_dragon}.json and
// data/apotheosis/loot_table/entity/{boss_drops,rare_boss_drops}.json.
StartupEvents.registry('item', event => {
    event.create("vanillaplusplus:duskfang").maxStackSize(1)
    event.create("vanillaplusplus:withering_maul").maxStackSize(1)
    event.create("vanillaplusplus:starfall_tachi").maxStackSize(1)
})
