#!/usr/bin/env python3
"""Build the distributable dedicated-server zip from server/ (after
build_server.py has synced it) - the server-side counterpart to
build_mrpack.py's client bundle.

Reuses build_server.py's sync (imported directly, not re-implemented) so
server/mods, server/config, server/kubejs, server/defaultconfigs,
server/user_jvm_args.txt, and server/server.properties are always current
against pack/mods.lock.json before zipping.

Design notes (DECISIONS.md "Release test + bundling architecture -
ADOPTED", and its "GitHub #141" entry for the unbundling change below):
- GitHub #141: this bundle no longer ships any THIRD-PARTY mod jar (i.e.
  every server/mods/*.jar entry in pack/mods.lock.json without a
  `local_path`) - many of the 113 mods this pack installs are under
  all-rights-reserved/custom licenses that don't clearly permit
  redistribution (see THIRD_PARTY.md). Instead the zip ships
  install_mods.py (scripts/install_mods.py, copied verbatim) plus a
  trimmed server-mods.lock.json (server-side, non-local entries only,
  generated fresh from pack/mods.lock.json every build) - the operator
  runs `python3 install_mods.py` once after extracting, which downloads
  each jar from its own origin (Modrinth/CurseForge CDN) and verifies it
  against the pinned sha1, mirroring the client `.mrpack`'s own
  URL-reference model. This project's own custom mods (`local_path`
  manifest entries - `vppintegration` as of GitHub #67/#124) remain
  shipped directly inside mods/, since we own their copyright.
- world/, logs/, cmd_fifo, crash-reports/, and any *.log are excluded -
  those are this dev session's runtime state, not something a fresh server
  install should start with.
- Also excluded: neoforge-installer.jar(+.log) (redundant - libraries/
  already has everything run.sh needs, no need to re-run the installer),
  .sable/ and cache/ (pure runtime caches regenerated on first launch by
  Sable and C2ME respectively), local/ (KubeJS dev-mode export/debug
  scripts - session-local, not release content).
- eula.txt is deliberately NOT included, even though this dev session's
  server/eula.txt already has eula=true from boot-testing - shipping that
  would silently pre-accept the EULA on the operator's behalf, which this
  project's release decision explicitly rejected. The bundle's own
  README.md documents the first-run requirement instead (loud and
  explicit, per the "a loud documented pre-acceptance is acceptable if the
  implementer finds first-run friction too high" fallback DECISIONS.md
  allowed - this implementation chose the plainer "just don't ship it"
  option over even a documented pre-acceptance).
- online-mode stays true (server.properties is synced verbatim from
  pack/server.properties, untouched by this script) - the shipped default
  per the recorded decision; L3 join-testing uses a separate test-only
  profile, never this one.
- ops.json/banned-*.json/usercache.json/whitelist.json ARE included: all
  four are genuinely empty ([]) in this repo's own pack/ source of truth
  (there is no pack/ copy of these - they're server-only runtime files
  NeoForge creates on first boot) - actually generated by the dedicated
  server itself before any player ever joined, so shipping them as empty
  scaffolding vs. letting the server recreate them on first boot makes no
  observable difference either way; included for a marginally faster/
  quieter first boot.

Usage: python3 scripts/build_server_bundle.py
"""
import json
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SERVER = ROOT / "server"
LOCKFILE = ROOT / "pack" / "mods.lock.json"
INSTALL_SCRIPT = ROOT / "scripts" / "install_mods.py"
VERSION_FILE = ROOT / "pack" / "VERSION"
VERSION = VERSION_FILE.read_text().strip()
OUT_FILE = ROOT / f"vanilla-plus-plus-server-{VERSION}.zip"

sys.path.insert(0, str(Path(__file__).resolve().parent))
import build_server  # noqa: E402  (reuse its sync logic, not duplicate it)

EXCLUDE_DIR_NAMES = {"world", "logs", "crash-reports", ".sable", "cache", "local", "patchouli_books"}
EXCLUDE_FILE_NAMES = {"cmd_fifo", "eula.txt", "neoforge-installer.jar", "neoforge-installer.jar.log"}


def third_party_jar_filenames(lock: dict) -> set:
    """Filenames (not paths) of every server-side mod jar in the lockfile
    that this project does NOT own the copyright to - i.e. every entry
    without a `local_path` (GitHub #141: these must not be redistributed
    inside the server zip, only referenced by URL+hash via install_mods.py).
    Client-only entries never land in server/mods/ in the first place
    (build_server.py already skips them), so filtering on side is not
    needed here, but excluding them is harmless if present."""
    return {
        mod["filename"]
        for mod in lock["mods"]
        if not mod.get("local_path")
    }


def server_mods_lock(lock: dict) -> dict:
    """Trimmed server-mods.lock.json shipped alongside install_mods.py:
    only the fields the installer needs (filename/url/hashes.sha1), only
    for non-local server-side mods (client-only entries are irrelevant to
    a dedicated server and are dropped)."""
    trimmed = []
    for mod in lock["mods"]:
        if mod.get("local_path"):
            continue
        if mod["side"] == "client":
            continue
        trimmed.append(
            {
                "slug": mod["slug"],
                "filename": mod["filename"],
                "url": mod["url"],
                "hashes": {"sha1": mod["hashes"]["sha1"]},
            }
        )
    return {"_comment": "Generated by scripts/build_server_bundle.py from pack/mods.lock.json - see install_mods.py.", "mods": trimmed}


def should_include(path: Path, exclude_filenames: frozenset) -> bool:
    rel = path.relative_to(SERVER)
    if rel.parts and rel.parts[0] in EXCLUDE_DIR_NAMES:
        return False
    if path.name in EXCLUDE_FILE_NAMES:
        return False
    if path.suffix == ".log":
        return False
    # GitHub #141: never ship a third-party mod jar in the distributable
    # zip, even though build_server.py's local sync (reused above to
    # refresh server/ before zipping) still downloads them all into
    # server/mods/ for local dev/boot-testing purposes.
    if rel.parts[:1] == ("mods",) and path.name in exclude_filenames:
        return False
    return True


README = """Vanilla++ dedicated server - v{version}

Requirements
------------
- Java 21 (Eclipse Adoptium/Temurin recommended). This bundle ships its own
  NeoForge libraries/ - you do NOT need to run the NeoForge installer.

First run
---------
1. Extract this zip anywhere.
2. Install the third-party mods (GitHub #141: this bundle does not ship
   them directly - see "Third-party mods" below):

     python3 install_mods.py

3. Read the Minecraft EULA: https://aka.ms/MinecraftEULA
4. This bundle deliberately does NOT pre-accept the EULA on your behalf.
   Create a file named `eula.txt` next to run.sh containing exactly:

       eula=true

   (or run the server once with `sh run.sh` / `run.bat` - it will refuse to
   start and write a blank eula.txt for you to edit, standard vanilla
   Minecraft behavior.)
5. Start the server:
     Linux/macOS: sh run.sh nogui
     Windows:     run.bat nogui   (drop `nogui` if you want the console GUI)

Third-party mods
-----------------
This bundle does NOT ship the ~113 third-party mod jars directly - many are
under all-rights-reserved/custom licenses that don't clearly permit
redistribution (see THIRD_PARTY.md in the source repo,
https://github.com/Guno327/vanillaplusplus/blob/main/THIRD_PARTY.md).
Instead this zip ships `install_mods.py` + `server-mods.lock.json`: running
`python3 install_mods.py` downloads each mod straight from its own origin
(Modrinth or CurseForge CDN) into `mods/` and verifies it against a pinned
sha1 checksum before use - the same URL-reference model the client
`.mrpack` has always used. Re-running it is safe/idempotent (only
re-downloads anything missing or checksum-mismatched); do this again after
extracting a newer release zip. Running on NixOS via this repo's
`nix/module.nix`? The module fetches these the declarative way instead
(per-mod fixed-output derivations) - you do not need to run this script at
all in that setup.

Memory / JVM tuning
--------------------
server/user_jvm_args.txt ships pre-tuned for this pack's size (Create, TFMG,
Stellaris, Apotheosis, world-exploration structure mods, etc.):
  -Xms6G -Xmx6G plus Aikar's flags (G1GC tuning - see
  https://docs.papermc.io/paper/aikars-flags for the rationale). Raise
  -Xmx/-Xms together (don't set them to different values) if you have more
  RAM available and see GC pauses in the logs; this pack realistically
  wants 6-8GB for a small/medium server.

online-mode
-----------
server.properties ships with online-mode=true (Mojang account verification
required to join) - the same as this pack's own dev server. Leave it as-is
unless you specifically need offline/cracked-client testing; if you do,
understand that's a security tradeoff you're opting into, not this bundle's
default.

What's in this zip
-------------------
config/, kubejs/, defaultconfigs/, libraries/, run.sh, run.bat,
server.properties, user_jvm_args.txt, install_mods.py,
server-mods.lock.json - everything needed to boot the server EXCEPT the
third-party mod jars themselves (run install_mods.py first, see above).
world/, logs/, and crash-reports/ are deliberately NOT included - you get a
fresh world on first boot, exactly like a brand new server install.

Version: {version}
Minecraft: 1.21.1, NeoForge: 21.1.235
"""


def build_readme() -> str:
    return README.format(version=VERSION)


def main():
    print("== build_server_bundle: syncing server/ via build_server.py ==")
    build_server.main()

    if OUT_FILE.exists():
        OUT_FILE.unlink()

    lock = json.loads(LOCKFILE.read_text())
    exclude_filenames = frozenset(third_party_jar_filenames(lock))
    trimmed_lock = server_mods_lock(lock)

    print(f"== zipping server/ -> {OUT_FILE} ==")
    print(f"   excluding {len(exclude_filenames)} third-party mod jars (GitHub #141) - see install_mods.py")
    file_count = 0
    with zipfile.ZipFile(OUT_FILE, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("README.md", build_readme())
        z.writestr("server-mods.lock.json", json.dumps(trimmed_lock, indent=2) + "\n")
        z.write(INSTALL_SCRIPT, "install_mods.py")
        file_count += 2
        for path in sorted(SERVER.rglob("*")):
            if not path.is_file():
                continue
            if not should_include(path, exclude_filenames):
                continue
            arcname = str(path.relative_to(SERVER))
            z.write(path, arcname)
            file_count += 1

    size_mb = OUT_FILE.stat().st_size / (1024 * 1024)
    print(f"wrote {OUT_FILE} ({file_count} files, {size_mb:.2f} MB)")


if __name__ == "__main__":
    main()
