#!/usr/bin/env python3
"""Build the distributable dedicated-server zip from server/ (after
build_server.py has synced it) - the server-side counterpart to
build_mrpack.py's client bundle.

Reuses build_server.py's sync (imported directly, not re-implemented) so
server/mods, server/config, server/kubejs, server/defaultconfigs,
server/user_jvm_args.txt, and server/server.properties are always current
against pack/mods.lock.json before zipping.

Design notes (DECISIONS.md "Release test + bundling architecture -
ADOPTED"):
- world/, logs/, cmd_fifo, crash-reports/, and any *.log are excluded -
  those are this dev session's runtime state, not something a fresh server
  install should start with.
- Also excluded: neoforge-installer.jar(+.log) (redundant - libraries/
  already has everything run.sh needs, no need to re-run the installer),
  .sable/ and cache/ (pure runtime caches regenerated on first launch by
  Sable and C2ME respectively), local/ (KubeJS dev-mode export/debug
  scripts - session-local, not release content).
- eula.txt is deliberately NOT included, even though this dev session's
  server/eula.txt already has eula=true from boot-testing - shipping that
  would silently pre-accept the EULA on the operator's behalf, which this
  project's release decision explicitly rejected. The bundle's own
  README.md documents the first-run requirement instead (loud and
  explicit, per the "a loud documented pre-acceptance is acceptable if the
  implementer finds first-run friction too high" fallback DECISIONS.md
  allowed - this implementation chose the plainer "just don't ship it"
  option over even a documented pre-acceptance).
- online-mode stays true (server.properties is synced verbatim from
  pack/server.properties, untouched by this script) - the shipped default
  per the recorded decision; L3 join-testing uses a separate test-only
  profile, never this one.
- ops.json/banned-*.json/usercache.json/whitelist.json ARE included: all
  four are genuinely empty ([]) in this repo's own pack/ source of truth
  (there is no pack/ copy of these - they're server-only runtime files
  NeoForge creates on first boot) - actually generated by the dedicated
  server itself before any player ever joined, so shipping them as empty
  scaffolding vs. letting the server recreate them on first boot makes no
  observable difference either way; included for a marginally faster/
  quieter first boot.

Usage: python3 scripts/build_server_bundle.py
"""
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SERVER = ROOT / "server"
VERSION_FILE = ROOT / "pack" / "VERSION"
VERSION = VERSION_FILE.read_text().strip()
OUT_FILE = ROOT / f"vanilla-plus-plus-server-{VERSION}.zip"

sys.path.insert(0, str(Path(__file__).resolve().parent))
import build_server  # noqa: E402  (reuse its sync logic, not duplicate it)

EXCLUDE_DIR_NAMES = {"world", "logs", "crash-reports", ".sable", "cache", "local", "patchouli_books"}
EXCLUDE_FILE_NAMES = {"cmd_fifo", "eula.txt", "neoforge-installer.jar", "neoforge-installer.jar.log"}


def should_include(path: Path) -> bool:
    rel = path.relative_to(SERVER)
    if rel.parts and rel.parts[0] in EXCLUDE_DIR_NAMES:
        return False
    if path.name in EXCLUDE_FILE_NAMES:
        return False
    if path.suffix == ".log":
        return False
    return True


README = """Vanilla++ dedicated server - v{version}

Requirements
------------
- Java 21 (Eclipse Adoptium/Temurin recommended). This bundle ships its own
  NeoForge libraries/ - you do NOT need to run the NeoForge installer.

First run
---------
1. Extract this zip anywhere.
2. Read the Minecraft EULA: https://aka.ms/MinecraftEULA
3. This bundle deliberately does NOT pre-accept the EULA on your behalf.
   Create a file named `eula.txt` next to run.sh containing exactly:

       eula=true

   (or run the server once with `sh run.sh` / `run.bat` - it will refuse to
   start and write a blank eula.txt for you to edit, standard vanilla
   Minecraft behavior.)
4. Start the server:
     Linux/macOS: sh run.sh nogui
     Windows:     run.bat nogui   (drop `nogui` if you want the console GUI)

Memory / JVM tuning
--------------------
server/user_jvm_args.txt ships pre-tuned for this pack's size (Create, TFMG,
Stellaris, Apotheosis, world-exploration structure mods, etc.):
  -Xms6G -Xmx6G plus Aikar's flags (G1GC tuning - see
  https://docs.papermc.io/paper/aikars-flags for the rationale). Raise
  -Xmx/-Xms together (don't set them to different values) if you have more
  RAM available and see GC pauses in the logs; this pack realistically
  wants 6-8GB for a small/medium server.

online-mode
-----------
server.properties ships with online-mode=true (Mojang account verification
required to join) - the same as this pack's own dev server. Leave it as-is
unless you specifically need offline/cracked-client testing; if you do,
understand that's a security tradeoff you're opting into, not this bundle's
default.

What's in this zip
-------------------
mods/, config/, kubejs/, defaultconfigs/, libraries/, run.sh, run.bat,
server.properties, user_jvm_args.txt - everything needed to boot the
server. world/, logs/, and crash-reports/ are deliberately NOT included -
you get a fresh world on first boot, exactly like a brand new server
install.

Version: {version}
Minecraft: 1.21.1, NeoForge: 21.1.235
"""


def build_readme() -> str:
    return README.format(version=VERSION)


def main():
    print("== build_server_bundle: syncing server/ via build_server.py ==")
    build_server.main()

    if OUT_FILE.exists():
        OUT_FILE.unlink()

    print(f"== zipping server/ -> {OUT_FILE} ==")
    file_count = 0
    with zipfile.ZipFile(OUT_FILE, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("README.md", build_readme())
        for path in sorted(SERVER.rglob("*")):
            if not path.is_file():
                continue
            if not should_include(path):
                continue
            arcname = str(path.relative_to(SERVER))
            z.write(path, arcname)
            file_count += 1

    size_mb = OUT_FILE.stat().st_size / (1024 * 1024)
    print(f"wrote {OUT_FILE} ({file_count} files, {size_mb:.2f} MB)")


if __name__ == "__main__":
    main()
