#!/usr/bin/env python3
"""Generate pack/kubejs/server_scripts/achievements.js - the Phase 6
replacement for FTB Quests' "Lifetime Achievements" chapter (see DESIGN.md's
Phase 6 section for why it moved out of FTB Quests: FTB Quests tracks all
progress at the FTB Teams level, with no way to keep this chapter per-player
once real multi-member teams exist).

Tracks the same four lifetime `minecraft:custom` stats as the old FTB Quests
chapter did, but reads them via KubeJS's own PlayerStatsJS wrapper
(player.stats.getMobKills()/getPlayTime()/getAnimalsBred()/getFishCaught() -
confirmed by decompiling dev.latvian.mods.kubejs.player.PlayerStatsJS in the
installed kubejs jar, not guessed) on a periodic tick, storing "how many
tiers of this chain has this player already been granted" in
player.persistentData (a CompoundTag stored on the player entity itself -
confirmed via KubeJS's WithPersistentData interface - so it's inherently
per-player and survives logout/restart, with zero FTB Teams/Quests
involvement at all).
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_FILE = ROOT / "pack" / "kubejs" / "server_scripts" / "achievements.js"

# (persistentData key, PlayerStatsJS getter, display label, skill category,
#  [thresholds]) - same four chains/thresholds as the old FTB Quests chapter.
CHAINS = [
    ("mob_kills", "getMobKills", "Monster Slayer", "swords", [50, 200, 800, 3200]),
    ("play_time", "getPlayTime", "Dedicated Settler", "mining", [24000, 96000, 384000, 1536000]),  # ticks (20/s)
    ("animals_bred", "getAnimalsBred", "Animal Husbandry", "building", [20, 80, 320, 1280]),
    ("fish_caught", "getFishCaught", "Angler", "swimming", [15, 60, 240, 960]),
]

TICK_INTERVAL = 100  # check every 5s - stats don't need tighter resolution than that


def js_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    lines = []
    lines.append("// GENERATED by scripts/gen_achievements.py - do not hand-edit, re-run the script instead.")
    lines.append("// Per-player lifetime achievement chains, replacing FTB Quests' old Lifetime Achievements")
    lines.append("// chapter (removed in Phase 6 - see gen_quests.py's note and DESIGN.md).")
    lines.append("const ACHIEVEMENT_CHAINS = [")
    for key, getter, label, category, thresholds in CHAINS:
        thresholds_js = ", ".join(str(t) for t in thresholds)
        lines.append(
            f"  {{ key: {js_string(key)}, getter: {js_string(getter)}, label: {js_string(label)}, "
            f"category: {js_string(category)}, thresholds: [{thresholds_js}] }},"
        )
    lines.append("]")
    lines.append("")
    lines.append(f"""
let achievementTickCounter = 0

ServerEvents.tick(event => {{
    achievementTickCounter++
    if (achievementTickCounter % {TICK_INTERVAL} !== 0) return

    for (const player of event.server.players) {{
        const data = player.persistentData
        for (const chain of ACHIEVEMENT_CHAINS) {{
            const progressKey = `achv_${{chain.key}}_tier`
            const currentTier = data.contains(progressKey) ? data.getInt(progressKey) : 0
            if (currentTier >= chain.thresholds.length) continue

            const statValue = player.stats[chain.getter]()
            const nextThreshold = chain.thresholds[currentTier]
            if (statValue < nextThreshold) continue

            const newTier = currentTier + 1
            const numeral = ["I", "II", "III", "IV"][currentTier]
            const xpAmount = 60 * Math.pow(4, currentTier)

            data.putInt(progressKey, newTier)
            player.server.runCommandSilent(`puffish_skills experience add ${{player.username}} ${{chain.category}} ${{xpAmount}}`)
            player.tell(`Achievement unlocked: ${{chain.label}} ${{numeral}} (+${{xpAmount}} ${{chain.category}} XP)`)
        }}
    }}
}})
""".strip("\n"))

    OUT_FILE.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT_FILE} ({len(CHAINS)} chains)")


if __name__ == "__main__":
    main()
