#!/usr/bin/env python3
"""Generate the tier-based sell-price table into
pack/kubejs/server_scripts/economy.js (both the price data and the /sell
command that reads it - kept in one file so there's no cross-script load-order
dependency between a data file and a logic file).

Pricing source: pack/progression/*.toml's own [items].locked lists - these
are the item ids that become available at each tier, already authored in
Phase 1 as this pack's own progression/difficulty signal. (Those files were
ProgressiveStages tier configs until #49 dropped that mod; they now live in
pack/progression/ as plain pack design data - read by generators, shipped to
nobody. The [items].locked lists are still this pack's tier manifest, they
just no longer drive a runtime lock.) Reusing
them here means "preset value... determined intelligently based on the tier/
difficulty" (instructions.md) falls directly out of decisions already made,
rather than needing a second, independent difficulty metric (e.g. recursive
crafting-cost analysis, which would be a much larger undertaking and would
likely just re-derive the same tier ordering anyway).

Any item NOT listed in one of those tier files (the overwhelming majority of
registered items - dirt, food, mob drops, undecorated vanilla blocks, etc.)
falls back to the TIER_0_PRICE. This is deliberate, not an oversight: pricing
every single registered item individually isn't tractable (and isn't what a
small 2-10 player private server needs - see instructions.md's clarified
scope), and instructions.md's "no limits on the ability to sell arbitrary
items" only requires that everything sell for *something*, not that every
item have a hand-tuned value.
"""
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STAGES_DIR = ROOT / "pack" / "progression"
OUT_FILE = ROOT / "pack" / "kubejs" / "server_scripts" / "economy.js"

# Sell price in spurs (Numismatics' base currency unit - 8 spurs/bevel,
# 16/sprocket, 64/cog, 512/crown, 4096/sun). Modest fractions of what each
# tier actually costs to reach, so selling can't out-earn playing normally.
TIER_ORDER = ["rootborn", "andesite_age", "brass_age", "precision_age", "induction_age", "starforged_age"]
TIER_PRICE = {
    "rootborn": 1,
    "andesite_age": 4,
    "brass_age": 16,
    "precision_age": 64,
    "induction_age": 256,
    "starforged_age": 1024,
}


def load_tier_items():
    prices = {}
    for tier in TIER_ORDER:
        f = STAGES_DIR / f"{tier}.toml"
        if not f.exists():
            continue
        data = tomllib.load(f.open("rb"))
        locked = data.get("items", {}).get("locked", [])
        for entry in locked:
            if not entry.startswith("id:"):
                continue
            item_id = entry[len("id:"):]
            # first tier that claims an item wins (shouldn't collide across
            # files, but be deterministic if it ever does)
            prices.setdefault(item_id, TIER_PRICE[tier])
    return prices


def js_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    prices = load_tier_items()

    lines = []
    lines.append("// GENERATED by scripts/gen_economy.py - do not hand-edit, re-run the script instead.")
    lines.append("// Tier-based sell pricing (in Numismatics spurs) + the /sell command that pays it out.")
    lines.append(f"const DEFAULT_PRICE = {TIER_PRICE['rootborn']}")
    lines.append("const ITEM_PRICES = {")
    for item_id, price in sorted(prices.items()):
        lines.append(f"  {js_string(item_id)}: {price},")
    lines.append("}")
    lines.append("")
    lines.append("function priceFor(itemId) {")
    lines.append("    return ITEM_PRICES[itemId] !== undefined ? ITEM_PRICES[itemId] : DEFAULT_PRICE")
    lines.append("}")
    lines.append("")
    lines.append("""
// Coin denominations in spurs, largest first, matching Numismatics' own Coin
// enum (net.createmod...Coin / dev.ithundxr.createnumismatics...Coin):
// spur=1, bevel=8, sprocket=16, cog=64, crown=512, sun=4096.
const COINS = [
    ["numismatics:sun", 4096],
    ["numismatics:crown", 512],
    ["numismatics:cog", 64],
    ["numismatics:sprocket", 16],
    ["numismatics:bevel", 8],
    ["numismatics:spur", 1],
]

function payCoins(player, totalSpurs) {
    let remaining = totalSpurs
    for (const [itemId, value] of COINS) {
        const count = Math.floor(remaining / value)
        if (count > 0) {
            player.give(Item.of(itemId, count))
            remaining -= count * value
        }
    }
}

ServerEvents.commandRegistry(event => {
    const { commands: Commands, arguments: Arguments } = event

    event.register(
        Commands.literal("sell")
            .executes(ctx => {
                const player = ctx.source.playerOrException
                const stack = player.getMainHandItem()
                if (!stack || stack.isEmpty()) {
                    player.tell("Hold an item to sell it to the vendor.")
                    return 0
                }
                const itemId = stack.id
                const count = stack.getCount()
                const unitPrice = priceFor(itemId)
                const total = unitPrice * count
                stack.setCount(0)
                payCoins(player, total)
                player.tell(`Sold ${count}x ${itemId} for ${total} spurs.`)
                return total
            })
    )
})
""".strip("\n"))

    OUT_FILE.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT_FILE} ({len(prices)} priced items + DEFAULT_PRICE={TIER_PRICE['rootborn']} fallback)")


if __name__ == "__main__":
    main()
