#!/usr/bin/env python3
"""Generate pack/kubejs/server_scripts/dailies.js - the Phase 6 replacement
for FTB Quests' old "Daily Bounties" chapter (removed for the same reason as
Lifetime Achievements - see gen_quests.py's note and DESIGN.md's Phase 6
section: FTB Quests progress is always tracked at the FTB Teams level, with
no way to keep specific chapters per-player once real multi-member teams
exist via Phase 6's team_mode flip).

Same bounty pool/rewards as the old FTB Quests chapter, reimplemented as:
- Kill bounties: passively tracked via EntityEvents.death (fires for any
  entity dying; event.source.entity is the killer, checked for
  .type == 'minecraft:player' - confirmed via decompiling
  dev.latvian.mods.kubejs.entity.LivingEntityDeathKubeEvent, which exposes
  getEntity()/getSource() -> .entity/.source in JS).
- Item bounties: turned in via a `/turnin` command (consumes matching items
  from the player's main hand, same ServerEvents.commandRegistry pattern as
  Phase 5's /sell) rather than a passive hook, since "turn in N items" has
  no natural passive trigger the way a kill does.
- Both use per-player progress counts and a real-world-time (Date.now(),
  not tick count - matches FTB Quests' own real-world repeat_cooldown
  semantics) cooldown-until timestamp in player.persistentData, so a bounty
  goes on a 24h (real time) cooldown once completed and resets automatically
  once that clears - inherently per-player, no FTB Teams/Quests involved.
- `/dailies` lets a player check their own status.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_FILE = ROOT / "pack" / "kubejs" / "server_scripts" / "dailies.js"

DAY_MS = 86400 * 1000

ITEM_BOUNTIES = [
    ("minecraft:cobblestone", 64, "mining", 20),
    ("minecraft:oak_log", 32, "building", 20),
    ("minecraft:coal", 32, "mining", 25),
    ("minecraft:iron_ingot", 16, "mining", 30),
    ("minecraft:wheat", 32, "building", 20),
    ("create:andesite_alloy", 16, "building", 30),
    ("minecraft:copper_ingot", 16, "mining", 30),
    ("minecraft:string", 24, "swords", 20),
    ("minecraft:leather", 16, "swords", 20),
    ("minecraft:sand", 64, "building", 20),
]

KILL_BOUNTIES = [
    ("minecraft:zombie", 15, "swords", 30),
    ("minecraft:skeleton", 15, "bows", 30),
    ("minecraft:spider", 15, "swords", 30),
    ("minecraft:creeper", 8, "swords", 35),
    ("minecraft:drowned", 10, "swimming", 35),
    ("minecraft:cod", 10, "swimming", 25),
    ("minecraft:rabbit", 10, "running", 25),
    ("minecraft:enderman", 5, "swords", 45),
]


def js_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def label_for(item_or_entity_id):
    return item_or_entity_id.split(":")[1].replace("_", " ").title()


def main():
    lines = []
    lines.append("// GENERATED by scripts/gen_dailies.py - do not hand-edit, re-run the script instead.")
    lines.append("// Per-player daily bounties, replacing FTB Quests' old Daily Bounties chapter (Phase 6).")
    lines.append(f"const DAY_MS = {DAY_MS}")
    lines.append("")
    lines.append("const ITEM_BOUNTIES = [")
    for item_id, count, category, xp in ITEM_BOUNTIES:
        lines.append(
            f"  {{ key: {js_string('item_' + item_id.replace(':', '_'))}, itemId: {js_string(item_id)}, "
            f"count: {count}, category: {js_string(category)}, xp: {xp}, label: {js_string(f'Turn in {count}x {label_for(item_id)}')} }},"
        )
    lines.append("]")
    lines.append("")
    lines.append("const KILL_BOUNTIES = [")
    for entity_id, count, category, xp in KILL_BOUNTIES:
        lines.append(
            f"  {{ key: {js_string('kill_' + entity_id.replace(':', '_'))}, entityId: {js_string(entity_id)}, "
            f"count: {count}, category: {js_string(category)}, xp: {xp}, label: {js_string(f'Slay {count}x {label_for(entity_id)}')} }},"
        )
    lines.append("]")
    lines.append("")
    lines.append("""
function getProgress(player, key) {
    const data = player.persistentData
    const progressKey = `daily_${key}_progress`
    const cooldownKey = `daily_${key}_cooldown_until`
    return {
        progress: data.contains(progressKey) ? data.getInt(progressKey) : 0,
        cooldownUntil: data.contains(cooldownKey) ? data.getLong(cooldownKey) : 0,
    }
}

function setProgress(player, key, progress) {
    player.persistentData.putInt(`daily_${key}_progress`, progress)
}

function completeBounty(player, bounty) {
    player.persistentData.putInt(`daily_${bounty.key}_progress`, 0)
    player.persistentData.putLong(`daily_${bounty.key}_cooldown_until`, Date.now() + DAY_MS)
    player.server.runCommandSilent(`puffish_skills experience add ${player.username} ${bounty.category} ${bounty.xp}`)
    player.tell(`Daily complete: ${bounty.label} (+${bounty.xp} ${bounty.category} XP)`)
}

function addBountyProgress(player, bounty, amount) {
    const { progress, cooldownUntil } = getProgress(player, bounty.key)
    if (Date.now() < cooldownUntil) return
    const newProgress = progress + amount
    if (newProgress >= bounty.count) {
        completeBounty(player, bounty)
    } else {
        setProgress(player, bounty.key, newProgress)
    }
}

EntityEvents.death(event => {
    const killer = event.source.entity
    if (!killer || killer.type !== "minecraft:player") return
    const victimType = event.entity.type
    for (const bounty of KILL_BOUNTIES) {
        if (bounty.entityId === victimType) {
            addBountyProgress(killer, bounty, 1)
        }
    }
})

ServerEvents.commandRegistry(event => {
    const { commands: Commands } = event

    event.register(
        Commands.literal("turnin")
            .executes(ctx => {
                const player = ctx.source.playerOrException
                const stack = player.getMainHandItem()
                if (!stack || stack.isEmpty()) {
                    player.tell("Hold a stack of a bounty item to turn it in.")
                    return 0
                }
                const itemId = stack.id
                const bounty = ITEM_BOUNTIES.find(b => b.itemId === itemId)
                if (!bounty) {
                    player.tell(`${itemId} isn't a daily bounty item.`)
                    return 0
                }
                const { progress, cooldownUntil } = getProgress(player, bounty.key)
                if (Date.now() < cooldownUntil) {
                    player.tell(`${bounty.label} is already complete for today.`)
                    return 0
                }
                const needed = bounty.count - progress
                const take = Math.min(needed, stack.getCount())
                stack.setCount(stack.getCount() - take)
                addBountyProgress(player, bounty, take)
                player.tell(`Turned in ${take}x ${itemId} (${Math.min(progress + take, bounty.count)}/${bounty.count})`)
                return take
            })
    )

    event.register(
        Commands.literal("dailies")
            .executes(ctx => {
                const player = ctx.source.playerOrException
                player.tell("--- Daily Bounties ---")
                for (const bounty of ITEM_BOUNTIES.concat(KILL_BOUNTIES)) {
                    const { progress, cooldownUntil } = getProgress(player, bounty.key)
                    if (Date.now() < cooldownUntil) {
                        const hoursLeft = Math.ceil((cooldownUntil - Date.now()) / 3600000)
                        player.tell(`${bounty.label}: done (resets in ~${hoursLeft}h)`)
                    } else {
                        player.tell(`${bounty.label}: ${progress}/${bounty.count}`)
                    }
                }
                return 1
            })
    )
})
""".strip("\n"))

    OUT_FILE.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT_FILE} ({len(ITEM_BOUNTIES)} item + {len(KILL_BOUNTIES)} kill bounties)")


if __name__ == "__main__":
    main()
