"""Shared helper for baking pack/VERSION into a KubeJS-readable constant on
BOTH the client and server build outputs - GitHub issue: notify a player
when their modpack version doesn't match the server's.

Used by both scripts/build_mrpack.py (writes into the .mrpack's
overrides/kubejs/startup_scripts/) and scripts/build_server.py (writes
straight into server/kubejs/startup_scripts/, which
scripts/build_server_bundle.py then zips up unchanged).

Deliberately NOT a file checked into pack/kubejs/ itself, the way this
project's other `gen_*.py` scripts commit their generated output
(pack/kubejs/startup_scripts/weapon_items.js etc. - see scripts/
gen_weapon_tiers.py). Those are regenerated by hand and re-committed
whenever their source data changes. pack/VERSION does not work that way:
mint-release.yml computes the release version and overwrites pack/VERSION
*on disk in the ephemeral runner's own checkout only* immediately before
calling build_mrpack.py/build_server_bundle.py - it deliberately never
commits that bump to main before building (see that workflow's own header
comment for the full causality argument: the release is the source of
truth for what shipped, not the other way around). A checked-in generated
kubejs file would therefore always be one version stale at the moment
that matters most - the actual mint. Generating it inline, at build time,
in both build scripts is the only way this constant can ever match the
version that's actually being baked into that same build's filename/
modrinth.index.json versionId.

startup_scripts run on both physical sides (client and server) before the
client/server split happens - see pack/kubejs/startup_scripts/
boss_weapons.js and weapon_items.js, both already shared - so a single
generated file under that directory reaches both
pack/kubejs/server_scripts/version_check.js and
pack/kubejs/client_scripts/version_check.js.
"""
import json

GENERATED_FILENAME = "generated_version.js"

# GitHub issue #94 follow-up ("warning before the crash from no mods"):
# the same pack/VERSION value, baked as a plain text file instead of a
# KubeJS constant, so mods-src/vppintegration's Java code (which runs
# during NeoForge's CONFIGURATION network phase - before any KubeJS
# script has a chance to run, and before a mismatched client ever reaches
# the PLAY phase/world) can read it too. See
# mods-src/vppintegration/.../network/PackVersionGate.java for the
# consumer and the full design writeup. Written under config/ (not
# kubejs/) on both sides, at the same "generated at build time, never
# committed" point as GENERATED_FILENAME above, for the same reason.
CONFIG_VERSION_RELATIVE_PATH = "vppplusplus/pack_version.txt"


def render_config_version_file(version: str) -> str:
    """Render the plain-text contents of CONFIG_VERSION_RELATIVE_PATH."""
    return version + "\n"


def render_version_script(version: str, source: str) -> str:
    """Render the generated startup script contents. `source` names the
    build script that produced this particular copy (purely a debugging
    aid if a player/dev ever has to diff a client's vs. server's copy)."""
    return (
        f"// GENERATED at build time by {source} from pack/VERSION - do not\n"
        "// hand-edit this file or commit it; it does not exist in the repo,\n"
        "// only in the built .mrpack / server bundle.\n"
        "// Read by pack/kubejs/server_scripts/version_check.js (server) and\n"
        "// pack/kubejs/client_scripts/version_check.js (client) for the\n"
        "// client/server version-mismatch notice.\n"
        f"global.VPP_PACK_VERSION = {json.dumps(version)};\n"
    )
